# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025-2026 Huawei Technologies Co., Ltd

# HINIC3 PMD tests
SRCS-y += test_hinic3_basic.c
SRCS-y += test_hinic3_hairpin.c

CFLAGS += -I$(RTE_SDK)/drivers/net/hinic3
CFLAGS += -I$(RTE_SDK)/drivers/net/hinic3/base
