; Global Configuration.
[hwoff_agent]
; offload_thread_num: Number of flow table offloading threads. The value range is {1, 2, 4}.
offload_thread_num=2
; max_flow_num: Maximum number of hardware flow tables, in million (M). The value range is {1, 2}, if run time mode is 1, support 4 also.
max_flow_num=2
; forward_cpu_mask: Core binding configuration for flow table offloading threads, e.g. "*, *".
forward_cpu_mask=8, 9
; control_cpu_mask: Core binding configuration for control threads, e.g. "*, *".
control_cpu_mask=10
; pf_pci_addr: NIC PCI address. The defalut value is "".
pf_pci_addr=""
; disk_usage: Maximum drive space usage of a file directory, in MB. The value range is [10, 10240].
disk_usage=1024
; hugepage_meminfo_statistic: Enable or disable hugepage memory statistics. The value can be either enable or disable.
hugepage_meminfo_statistic=enable
; packet_forward_mode: Packet forwarding mode. The value range is {0, 1}. 0: high bandwidth mode, 1: low latency mode.
packet_forward_mode=0
; run_time_mode: DPAK runtime modes in different scenarios. 
run_time_mode=0x0100
; bond_hash_policy: efficient bond hash policy selection. The value range is {0, 1}. 0: efficient hash policy, 1: standard hash policy, default 0.
bond_hash_policy=0
; pcap_cpu: CPU configuration for the packet capture threads. The value range is [0, 23].
pcap_cpu=0

; Port Configuration.
[hwoff_port]
; bond_rx_depth: RX queue depth of the bond port. The value range is [256, 8192].
bond_rx_depth=2048
; bond_tx_depth: TX queue depth of the bond port. The value range is [256, 8192].
bond_tx_depth=2048
; vport_rx_depth: RX queue depth of the VF and PF ports. The value range is [256, 8192].
vport_rx_depth=512
; vport_tx_depth: TX queue depth of the VF and PF ports. The value range is [256, 8192].
vport_tx_depth=512
; max_queue_num: Number of VirtIO queues on a port. The value range is [1, 32]. When run_time_mode is 1, this configuration item does not take effect.
max_queue_num=4
; upcall_queue_num: Number of upcall queues on a port. The value range is [1, 16], and the value must be the same as that of rte_eth_dev_configure. When run_time_mode is 1, this configuration item does not take effect.
upcall_queue_num=4
; mbuf_size: The dataroom size of mempool used by the hiovs3 driver.
mbuf_size=2176
; virtio_queue_depth: Number of port virtio queue depthe, support scope is [128, 32768].
virtio_queue_depth=1024

; Flow Configuration.
[hwoff_flow]
; flow_max_idle: Hardware flow table aging time. The value range is [30000, 500000].
flow_max_idle=200000

; QoS Configuration.
[hwoff_QoS]
; Types of multi-level QoS settings. The value rannge is {port_pps, port_bps, net_pps, net_bps}.Just support in run_time_mode = 1.
qos_level=port_bps,port_pps,net_bps,net_pps
