/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2025 Huawei Technologies Co., Ltd
 */

#ifndef HINIC3_ERROR_STATS_H
#define HINIC3_ERROR_STATS_H
#include <stdint.h>
#include "hinic3_flow_agent_enum.h"
/** 错误类型名 命名格式
 * HINIC3_ERSTAT_FLOW_WARNING_BRAODCAST_PKT
 * |--- 前缀 ---|模块|错误类型|-- 错误信息--|
 * 模块名简称
 * [HINIC3_COMMON_RESOURCE] COMMON:通用工具模块
 * [HINIC3_CAPTURE] CAPTURE:抓包模块
 * [HINIC3_COMMAND] COMMAND:命令行模块
 * [HINIC3_CT_OFFLOAD] CT:ct卸载模块
 * [HINIC3_DRIVER_ADAPTER] DRIVER:驱动适配模块
 * [HINIC3_FLOWS] FLOWS:流表模块
 * [HINIC3_OVS_FLOW] OVSOFF: OVS流表卸载模块
 * [HINIC3_INIT] INIT:初始化模块
 * [HINIC3_POLICY] POLICY:卸载策略模块
 * [HINIC3_PORTS] PORTS:端口模块
 * [HINIC3_QOS] QOS:qos模块
 * [HINIC3_SECURITY_FILTER] FILTER:安全过滤模块
 * [HINIC3_UFID_MAP] UFID:ufid管理
 * [HINIC3_OVS_MEMPOOL] -
 * [HINIC3_OVS_UFID_MEMPOOL] -
 * [HINIC3_OVS_UFID_MAP] OVSUFID:OVS ufid管理
 * [HINIC3_PACKET_PARSE] PACKET:OVS 解包模块
 * [HINIC3_OVS_SMAC] -
 * [HINIC3_OVS_HINIC3_PRIVATE] -
 * [HIOVS_MEM] -
 */


enum hinic3_errstat_type {
    HINIC3_ERRSTAT_START,
    // 通用工具模块
    HINIC3_COMMON_ERROR_ERRSTAT_TYPE_OUT_OF_BOUND,
    HINIC3_COMMON_ERROR_ERRSTAT_TYPE_NO_INFO,
    HINIC3_COMMON_ERROR_ERRSTAT_INPUT_NULL,
    // CT 卸载模块
    HINIC3_CT_OFFLOAD_ERROR_CT_NOT_READY_TO_OFFLOAD,
    HINIC3_CT_OFFLOAD_ERROR_CT_CHECK_FAIL,
    HINIC3_CT_OFFLOAD_WARNING_CT_NOT_READY,
    HINIC3_CT_OFFLOAD_ERROR_CLEAN_ID_NOT_FOUND,
    HINIC3_CT_OFFLOAD_ERROR_CT_CHECK_CONN_FAILED,
    HINIC3_CT_OFFLOAD_ERROR_GET_INFO_ID_NOT_FOUND,
    HINIC3_CT_OFFLOAD_ERROR_CHECK_ALG_CTRL,
    HINIC3_CT_OFFLOAD_ERROR_RECIRCLED_NON_TCP,
    HINIC3_CT_OFFLOAD_ERROR_GET_EXIST_CONN_NOT_FOUND,
    HINIC3_CT_OFFLOAD_WARNING_CT_NOT_CONNECT,
    HINIC3_CT_OFFLOAD_ERROR_ADD_CT_NAT_ACTION_SEARCH_FAIL,
    HINIC3_CT_OFFLOAD_ERROR_CT_SEARCH_FAIL,
    HINIC3_CT_OFFLOAD_WARNING_SET_CT_NOT_NAT,
    HINIC3_CT_OFFLOAD_WARNING_ADD_CT_NOT_NAT,
    HINIC3_CT_OFFLOAD_ERROR_CT_REVERT_CONN_IS_NULL,
    HINIC3_CT_OFFLOAD_ERROR_CT_REVERT_CONN_IS_NOT_NAT,
    HINIC3_CT_OFFLOAD_ERROR_INSERT_CT_ACTION_FAIL,
    HINIC3_CT_OFFLOAD_ERROR_IGNORE_CT_FOR_PUSH,
    HINIC3_CT_OFFLOAD_ERROR_CALLBACK_GET_CONN_BY_KEY_FAIL,
    HINIC3_CT_OFFLOAD_ERROR_CALLBACK_OFFLOAD_FAIL,
    HINIC3_CT_OFFLOAD_ERROR_CALLBACK_SEARCH_CONN_FAIL,
    // 流表模块 - EMC 基础操作
    HINIC3_FLOWS_ERROR_GLOBAL_CFG_SET_EMC_SAMPLE,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_PROCESS_FLOW_KEY_FAIL,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_PROCESS_FLOW_MASK_FAIL,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_MODIFY_PROCESS_FLOW_KEY_FAIL,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_CHECK_OFFLOAD_REPEATED,
    HINIC3_FLOWS_WARNING_EMC_OFFLOAD_CHECK_OFFLOAD_EXIT_GAP,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_CHECK_OFFLOAD_ONGOING,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_INSERT_INTO_HMAP_FAIL,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_PARSE_FLOW_ACTION,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_MODIFY_PARSE_FLOW_ACTION,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_CALL_HARDWARE_FUNC,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_MODIFY_CALL_HARDWARE_FUNC,
    // 流表模块 - FLOW 删除
    HINIC3_FLOWS_ERROR_AGE_EMC_DEL_FLOW_IN_HMAP,
    HINIC3_FLOWS_ERROR_EMC_DEL_FLOW_IN_HMAP,
    HINIC3_FLOWS_ERROR_EMC_DEL_FLOW_QOS,
    HINIC3_FLOWS_ERROR_EMC_DEL_HARD_FLOW,
    // 流表模块 - EMC OFFLOAD
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_FLOW_MEGA_FLOW_ALLOC,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_FLOW_CREATE_ECOLOGY_ALLOC,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_FLOW_ALLOC,
    HINIC3_FLOWS_ERROR_EMC_OFFLOAD_AGENT_NO_INIT,
    HINIC3_FLOWS_ERROR_EMC_ETH_FLOW_CREATE_ECOLOGY_NO_INIT,
    HINIC3_FLOWS_ERROR_EMC_FLOW_NOT_OFFLOAD,
    // 流表模块 - SESSION 删除
    HINIC3_FLOWS_ERROR_EMC_ACL_DEL_FLOW_IN_SESSION,
    HINIC3_FLOWS_ERROR_EMC_AGE_DEL_FLOW_IN_SESSION,
    HINIC3_FLOWS_ERROR_EMC_CMCC_DEL_FLOW_IN_SESSION,
    HINIC3_FLOWS_ERROR_EMC_MODIFY_DEL_FLOW_IN_SESSION,
    HINIC3_FLOWS_ERROR_EMC_MEGA_DEL_FLOW_IN_SESSION,
    // 流表模块 - FLUSH
    HINIC3_FLOWS_ERROR_EMC_FLUSH_HARD_FLOW,
    HINIC3_FLOWS_ERROR_EMC_FLUSH_MPOOL,
    HINIC3_FLOWS_ERROR_EMC_FLUSH_MIRROR_SESSION,
    HINIC3_FLOWS_ERROR_EMC_FLUSH_MEGA_MIRROR_SESSION,
    // 流表模块 - EMC DUMP
    HINIC3_FLOWS_ERROR_EMC_DUMP_START,
    HINIC3_FLOWS_ERROR_EMC_DUMP_START_HARD,
    HINIC3_FLOWS_ERROR_EMC_DUMP_DONE,
    HINIC3_FLOWS_ERROR_EMC_DUMP_DONE_HARD,
    HINIC3_FLOWS_ERROR_EMC_DUMP_NEXT,
    HINIC3_FLOWS_ERROR_EMC_DUMP_NEXT_MEM,
    // 流表模块 - ACL
    HINIC3_FLOWS_ERROR_ACL_FLOW_HARDWARE_DEL,
    HINIC3_FLOWS_ERROR_ACL_FLOW_TABLE_DEL,
    HINIC3_FLOWS_ERROR_ACL_FLOW_OFFLOAD,
    HINIC3_FLOWS_ERROR_ACL_DUMP_START,
    HINIC3_FLOWS_ERROR_ACL_DUMP_START_HARD,
    HINIC3_FLOWS_ERROR_ACL_DUMP_DONE,
    HINIC3_FLOWS_ERROR_ACL_DUMP_NEXT,
    HINIC3_FLOWS_ERROR_ACL_DUMP_NEXT_HARD,
    HINIC3_FLOWS_ERROR_ACL_FLOW_QUERY_INPUT_NULL,
    HINIC3_FLOWS_ERROR_ACL_FLOW_QUERY_DUPLICATE_MEM,
    HINIC3_FLOWS_ERROR_ACL_FLOW_DELETE_DUPLICATE_MEM,
    // 流表模块 - DP DUMP
    HINIC3_FLOWS_ERROR_DP_DUMP_START,
    HINIC3_FLOWS_ERROR_DP_DUMP_DONE,
    HINIC3_FLOWS_ERROR_DP_DUMP_NEXT,
    HINIC3_FLOWS_ERROR_DP_DUMP_FORMAT,
    HINIC3_FLOWS_ERROR_DP_DUMP_ITEM_BUILD_FAIL,
    HINIC3_FLOWS_ERROR_DP_DUMP_ACTION_BUILD_FAIL,
    HINIC3_FLOWS_ERROR_DP_DUMP_PORT_SESSION_ID_ERR,
    // 流表模块 - MEGA DUMP
    HINIC3_FLOWS_ERROR_MEGA_DUMP_START,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_START_HARD,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_DONE,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_DONE_HARD,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_NEXT,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_NEXT_HARD,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_ACTION_TYPE,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_ITEM_TYPE,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_INPORT_ITEM,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_OUTPORT_ITEM,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_INPORT,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_VLAN,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_VXLAN,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_ETH,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_ITEM_TYPE,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_ACTION_TYPE,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_SET_SMAC,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_SET_DMAC,
    HINIC3_FLOWS_ERROR_MEGA_DUMP_FORMAT_OUTPORT,
    // 流表模块 - MEGA OFFLOAD
    HINIC3_FLOWS_ERROR_MEGA_FLOW_OFFLOAD,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_OFFLOAD_REPEATED,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_OFFLOAD_DRV_CALL,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_ETH_ITEM,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_VLAN_ITEM,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_INPORT_ITEM,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_VXLAN_ITEM,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_OUTPORT_ACTION,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_SET_SMAC_ACTION,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_SET_DMAC_ACTION,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_VXLAN_ENCAP_ACTION,
    HINIC3_FLOWS_ERROR_MEGA_OFFLOAD_OUTPORT_WRONG,
    // 流表模块 - MEGA FLOW 操作
    HINIC3_FLOWS_ERROR_MEGA_MPOOL_FLUSH,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_FLUSH,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_QUERY,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_QUERY_INPUT_NULL,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_DELETE,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_KEY_PARSE,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_ACTION_PARSE,
    // 流表模块 - DPHASH
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_OFFLOAD,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_DELETE_FROM_SW_FAIL,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_DELETE_FROM_HW_FAIL,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_GET_BY_KEY_FAIL,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_EXIST,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_INSERT_HMAP_FAIL,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_EXIST_WHILE_HW_NOT,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_PARSE_KEY_FAIL,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_PARSE_ACTION_FAIL,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_MGMT_PUT_FAIL,
    HINIC3_FLOWS_ERROR_DPHASH_FLOW_DELETE_SW_BY_KEY_GET_FAIL,
    HINIC3_FLOWS_ERROR_CALLBACK_DPHASH_FLOW_PUT,
    HINIC3_FLOWS_ERROR_CALLBACK_DP_HASH_SET_UFID_FLOW,
    // 流表模块 - CALLBACK
    HINIC3_FLOWS_ERROR_CALLBACK_FLOW_PUT_INFO,
    HINIC3_FLOWS_ERROR_CALLBACK_MODIFY_FLOW_PUT,
    HINIC3_FLOWS_ERROR_CALLBACK_SET_UFID_IN_RTE_FLOW,
    // 流表模块 - METER
    HINIC3_FLOWS_ERROR_METER_TYPE,
    HINIC3_FLOWS_ERROR_METER_ACTION,
    HINIC3_FLOWS_ERROR_METER_NOT_FOUND,
    HINIC3_FLOWS_ERROR_NEXT_METER_NOT_FOUND,
    HINIC3_FLOWS_ERROR_SET_FLOW_METER_NOT_FOUND,
    HINIC3_FLOWS_ERROR_SET_FLOW_NEXT_METER_NOT_FOUND,
    // 流表模块 - QOS
    HINIC3_FLOWS_ERROR_FLOW_QOS_FULL,
    HINIC3_FLOWS_ERROR_FLOW_SET_QOS_HOVS,
    HINIC3_FLOWS_ERROR_FLOW_DEL_QOS_HOVS,
    HINIC3_FLOWS_ERROR_FLOW_DEL_NEXT_QOS_HOVS,
    HINIC3_FLOWS_ERROR_FLOW_QOS_PACKET_MODE,
    // 流表模块 - SAMPLE
    HINIC3_FLOWS_ERROR_SAMPLE_ACTION,
    HINIC3_FLOWS_ERROR_SAMPLE_ACTION_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_ACTION_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_ACTION,
    HINIC3_FLOWS_ERROR_SAMPLE_PORT_ID_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_PORT_ID,
    HINIC3_FLOWS_ERROR_SAMPLE_ACTION_SET,
    HINIC3_FLOWS_ERROR_SAMPLE_VXLAN_ENCAP,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_VXLAN_ENCAP,
    HINIC3_FLOWS_ERROR_SAMPLE_UDP_ITEM_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_UDP_ITEM_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_VXLAN_ITEM_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_VXLAN_ITEM_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_IPV6_ITEM_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_IPV6_ITEM_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_ETH_ITEM_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_ETH_ITEM_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_VLAN_ITEM_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_VLAN_ITEM_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_IPV4_ITEM_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_IPV4_ITEM_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_NVGRE_ITEM_NULL,
    HINIC3_FLOWS_ERROR_MEGA_SAMPLE_NVGRE_ITEM_NULL,
    HINIC3_FLOWS_ERROR_SAMPLE_SHIM_ITEM,
    // 流表模块 - SESSION
    HINIC3_FLOWS_ERROR_SESSION_FULLED,
    HINIC3_FLOWS_ERROR_SESSION_UNUSED,
    HINIC3_FLOWS_ERROR_SESSION_RATIO,
    // 流表模块 - HW_STATS
    HINIC3_FLOWS_ERROR_GET_HW_STATS_BY_UFID,
    // 流表模块 - MANY_OUTPUT
    HINIC3_FLOWS_WARNING_OFFLOAD_CHECK_ACTIONS_MANY_OUTPUT,
    HINIC3_FLOWS_WARNING_MANY_OUTPUT,
    // 流表模块 - VXLAN_OFFSET
    HINIC3_FLOWS_ERROR_DP_FLOW_NO_VXLAN_ACTION_OFFSET,
    HINIC3_FLOWS_ERROR_MEGA_FLOW_NO_VXLAN_ACTION_OFFSET,
    HINIC3_FLOWS_ERROR_FLOW_NO_VXLAN_ACTION_OFFSET,
    // 流表模块 - FLOW 类型错误
    HINIC3_FLOWS_ERROR_WRONG_CREATE_FLOW_TYPE,
    HINIC3_FLOWS_ERROR_WRONG_FLUSH_FLOW_TYPE,
    HINIC3_FLOWS_ERROR_INPUT_NOT_HIOVS,
    // 流表模块 - UFID/TIME/FLUSH
    HINIC3_FLOWS_ERROR_UFID_MAP_MPOOL_FLUSH,
    HINIC3_FLOWS_ERROR_GET_TIME_STAMP,
    HINIC3_FLOWS_ERROR_FLOW_FLUSH_ALL_INPUT_NULL,
    // 流表模块 - DUMP_INPUT
    HINIC3_FLOWS_ERROR_DUMP_INPUT_CHECK_PTHREAD,
    HINIC3_FLOWS_ERROR_DUMP_INPUT_CHECK_TYPE,
    HINIC3_FLOWS_ERROR_DEV_DUMP_NULL,
    // 流表模块 - FLOW 基础错误
    HINIC3_FLOWS_ERROR_NO_EXIST_FLOW,
    HINIC3_FLOWS_ERROR_FLOW_NOT_READY,
    HINIC3_FLOWS_ERROR_FLOW_BLOCK_ID_ERR,
    HINIC3_FLOWS_ERROR_RX_HW_AGE_ERR,
    HINIC3_FLOWS_ERROR_HIGH_PRIORITY_ETH_NULL,
    HINIC3_FLOWS_ERROR_HIGH_PRIORITY_IPV6_NULL,
    HINIC3_FLOWS_ERROR_HIGH_PRIORITY_WRONG_ITEM,
    HINIC3_FLOWS_ERROR_HIGH_PRIORITY_UPCALL_SET_FAIL,
    HINIC3_FLOWS_ERROR_HIGH_PRIORITY_BOND_DEV_NULL,
    HINIC3_FLOWS_ERROR_FLOW_FLUSH_DEV_NULL,
    HINIC3_FLOWS_ERROR_FLOW_FLUSH_GET_PORT_ID_FAIL,
    HINIC3_FLOWS_ERROR_FLOW_FLUSH_BY_PORT_FAIL,
    // 流表模块 - GET_PORT_ID 错误
    HINIC3_FLOWS_ERROR_GET_PORT_ID_INPUT_NULL,
    HINIC3_FLOWS_ERROR_GET_PORT_ID_NOMEM,
    HINIC3_FLOWS_ERROR_GET_PORT_ID_INFO_GET_FAILED,
    HINIC3_FLOWS_ERROR_GET_PORT_ID_NETDEV_CLASS_NULL,
    HINIC3_FLOWS_ERROR_GET_PORT_ID_PORT_ID_INVALID,
    // 流表模块 - IS_ETHDEV 错误
    HINIC3_FLOWS_ERROR_IS_ETHDEV_NETDEV_CLASS_NULL,
    HINIC3_FLOWS_ERROR_IS_ETHDEV_DEV_INFO_ALLOC_FAIL,
    HINIC3_FLOWS_ERROR_IS_ETHDEV_DEV_INFO_GET_FAIL,
    HINIC3_FLOWS_ERROR_IS_ETHDEV_TYPE_NOT_DPDK,
    HINIC3_FLOWS_ERROR_IS_ETHDEV_PORT_ID_INVALID,
    // 流表模块 - IS_SUPPORT_OFFLOAD 错误
    HINIC3_FLOWS_ERROR_IS_SUPPORT_OFFLOAD_CLASS_NULL,
    HINIC3_FLOWS_ERROR_IS_SUPPORT_OFFLOAD_TYPE_NULL,
    HINIC3_FLOWS_ERROR_FLEXDA_FUZZY_FLOW_COPY_RAW_KEY_ITEM_FAIL,
    HINIC3_FLOWS_ERROR_IS_SUPPORT_OFFLOAD_NETDEV_NULL,
    HINIC3_FLOWS_ERROR_IS_SUPPORT_OFFLOAD_UNSUPPORTED,
    // OVSOFF
    HINIC3_OVS_FLOW_ERROR_FLOW_RECIRC_BY_PACKET,
    HINIC3_OVS_FLOW_ERROR_FLOW_GENERATE_BY_PACKET,
    HINIC3_OVS_FLOW_ERROR_OFFLOAD_BY_PACKET,
    HINIC3_OVS_FLOW_ERROR_CREATE_INPUT_NULL,
    HINIC3_OVS_FLOW_ERROR_PARSE_INFO_FAIL,
    HINIC3_OVS_FLOW_ERROR_INSERT_POLICY_ID_FAIL,
    HINIC3_OVS_FLOW_ERROR_INSERT_MEGA_UFID_FAIL,
    HINIC3_OVS_FLOW_ERROR_DESTROY_PARAM_INVALID,
    HINIC3_OVS_FLOW_ERROR_DESTROY_FAILED,
    HINIC3_OVS_FLOW_ERROR_CONSTRUCT_ETH_FAIL,
    HINIC3_OVS_FLOW_ERROR_CONSTRUCT_IP_FAIL,
    HINIC3_OVS_FLOW_ERROR_ALLOC_TCP_ITEM_FAIL,
    HINIC3_OVS_FLOW_ERROR_ALLOC_UDP_ITEM_FAIL,
    HINIC3_OVS_FLOW_ERROR_ALLOC_ICMP_ITEM_FAIL,
    HINIC3_OVS_FLOW_ERROR_NOT_SUPPORT_L4_PROTOCOL,
    HINIC3_OVS_FLOW_ERROR_CONSTRUCT_5_TUPLES_FAIL,
    HINIC3_OVS_FLOW_ERROR_PARSE_RAW_IP_FAIL,
    HINIC3_OVS_FLOW_ERROR_CONSTRUCT_TUPLES_FAIL,
    HINIC3_OVS_FLOW_ERROR_INSERT_ACTION_FAIL,
    HINIC3_OVS_FLOW_ERROR_PACKET_PARSE_INPUT_NULL,
    // 初始化模块
    HINIC3_FLOWS_ERROR_FORWARD_ENGINE_NOT_READY,
    HINIC3_FLOWS_ERROR_SET_FORWARD_MODE_NOT_READY,
    // 卸载策略模块
    HINIC3_POLICY_WARNING_OFFLOAD_DELAY,
    HINIC3_POLICY_ERROR_OFFLOAD_LIMITS,
    HINIC3_POLICY_ERROR_NO_CONN_TABLE,
    HINIC3_POLICY_ERROR_NOT_USER_PERMISSIONS_0,
    HINIC3_POLICY_ERROR_USER_TABLE_NUM_EXCEED_PERMISSIONS,
    HINIC3_POLICY_ERROR_NOT_USER_PERMISSION,
    HINIC3_POLICY_ERROR_DUPLICATE_OFFLOAD,
    HINIC3_POLICY_ERROR_ILLEGAL_INPUT,
    HINIC3_POLICY_ERROR_ILLEGAL_OFFLOAD_TIME,
    HINIC3_POLICY_WARNING_CHECK_NO_OFFLOAD,
    HINIC3_POLICY_ERROR_REACH_USER_LIMITS,
    HINIC3_POLICY_WARNING_INTERNAL_ERROR,
    HINIC3_POLICY_WARNING_LOW_SPEED_FLOW_DEL,
    HINIC3_POLICY_ERROR_LOW_SPEED,
    HINIC3_POLICY_WARNING_HASH_TABLE_DEL_FAIL,
    HINIC3_POLICY_ERROR_CALLBACK_ILLEGAL_INPUT,
    HINIC3_POLICY_WARNING_DUPLICATE_CHECK,
    HINIC3_POLICY_WARNING_TIME_GET_FAILED,
    HINIC3_POLICY_WARNING_TIME_BACKWARD,
    HINIC3_POLICY_ERROR_DEL_HW_FLOW_FAIL,
    HINIC3_POLICY_ERROR_ILLEGAL_DELAY_TIME,
    HINIC3_POLICY_ERROR_ILLEGAL_TIME,
    HINIC3_POLICY_WARNING_LOW_PPS_DELAY,
    // 端口模块
    HINIC3_PORTS_ERROR_HOVS_RTE_RX_BURST_NULL,
    HINIC3_PORTS_ERROR_HOVS_RTE_TX_BURST_NULL,
    HINIC3_PORTS_ERROR_HOVS_RTE_TX_BURST_QUEUE_ID_OUT_OF_RANGE,
    HINIC3_FLOWS_WARNING_OFFLOAD_DISABLE,
    HINIC3_PORTS_ERROR_VIRTUAL_QUEUE_RECV_PKTS_DISTRIBUTE_DROP,
    HINIC3_PORTS_ERROR_VF_RX_QUEUE_INVALID,
    HINIC3_PORTS_ERROR_BOND_RX_QUEUE_INVALID,
    HINIC3_PORTS_ERROR_VIRTUAL_RX_QUEUE_INVALID,
    HINIC3_PORTS_ERROR_VF_TX_QUEUE_INVALID,
    HINIC3_PORTS_ERROR_BOND_TX_QUEUE_INVALID,
    HINIC3_PORTS_ERROR_DEV_SHARE_UPCALL_PRIVATE_DATA_NULL,
    HINIC3_PORTS_ERROR_DEV_COMMOM_PORT_PRIVATE_DATA_NULL,
    HINIC3_PORTS_ERROR_DEV_VF_XMIT_PRIVATE_DATA_NULL,
    HINIC3_PORTS_ERROR_DEV_BOND_RECV_PRIVATE_DATA_NULL,
    HINIC3_PORTS_ERROR_DEV_BOND_XMIT_PRIVATE_DATA_NULL,
    HINIC3_FLOWS_ERROR_FLOW_QUERY_CMCC_INPUT_NULL,
    HINIC3_FLOWS_ERROR_FLOW_QUERY_INPUT_NULL,
    HINIC3_FLOWS_ERROR_FLOW_CREATE_DEV_DEV_INPUT_NULL,
    HINIC3_FLOWS_ERROR_FLOW_CREATE_ATTR_INPUT_NULL,
    HINIC3_FLOWS_ERROR_FLOW_CREATE_ERROR_INPUT_NULL,
    HINIC3_FLOWS_ERROR_FLOW_CREATE_INPUT_NULL,
    HINIC3_FLOWS_ERROR_FLOW_DEL_INPUT_NULL,
    HINIC3_FLOWS_ERROR_EMC_FLOW_GET_PORT_ID,
    HINIC3_FLOWS_ERROR_ETH_FLOW_GET_PORT_ID,
    HINIC3_FLOWS_ERROR_UPCALL_PRIORITY,
    HINIC3_FLOWS_WARNING_BOND_SLAVE_DETECT_PKT,
    HINIC3_FLOWS_ERROR_BOND_SLAVE_DETECT_NO_MATCH,
    // qos模块
    HINIC3_FLOWS_ERROR_SET_MULTI_QOS,
    // ovs 解包模块
    HINIC3_OVS_FLOW_ERROR_FLOW_NO_OUTPUT_PORT,
    HINIC3_OVS_FLOW_ERROR_FLOW_MUTIL_OUTPUT_PORT,
    HINIC3_OVS_FLOW_ERROR_OFFLOAD_FULLKEY_ADD_RECIRCLE_VPORT_FAIL,
    HINIC3_OVS_FLOW_ERROR_OFFLOAD_FULLKEY_ADD_VPORT_FAIL,
    HINIC3_OVS_FLOW_ERROR_OFFLOAD_PARSE_HDR_FAIL,
    HINIC3_OVS_FLOW_ERROR_MBUF_GET_FAIL,
    HINIC3_OVS_FLOW_ERROR_PARSE_ACTION,
    HINIC3_OVS_FLOW_ERROR_PARSE_PKT_EXTRACT,
    HINIC3_OVS_FLOW_ERROR_PARSE_PKT_INFO,
    HINIC3_OVS_FLOW_ERROR_PARSE_HDR_PARSE,
    HINIC3_OVS_FLOW_ERROR_IP_FRAGMENT,
    HINIC3_OVS_FLOW_ERROR_IPV6_FRAGMENT,
    HINIC3_OVS_FLOW_ERROR_IPV6_ICMP_NOT_ECHO,
    HINIC3_OVS_FLOW_ERROR_BROADCAST_PKT,
    HINIC3_OVS_FLOW_ERROR_NO_PKT_INFO,
    HINIC3_OVS_FLOW_ERROR_EXTRACT_PKT,
    HINIC3_OVS_FLOW_ERROR_LCORE_IDX_OUT_OF_RANGE,
    HINIC3_OVS_FLOW_ERROR_TRANS_KEY,
    HINIC3_OVS_FLOW_ERROR_PROC_OFFLOAD_PKTS_FAILED,
    HINIC3_OVS_FLOW_ERROR_OUTPUT_ACTION_NULL,
    HINIC3_OVS_FLOW_ERROR_VLAN_PCP_NULL,
    HINIC3_OVS_FLOW_ERROR_VLAN_VID_NULL,
    HINIC3_OVS_FLOW_ERROR_COPY_RECIRC_ACTIONS_FAIL,
    HINIC3_OVS_FLOW_ERROR_FLOW_ALLOC_FAIL,
    HINIC3_OVS_FLOW_ERROR_MEGA_UFID_INSERT_FAIL,
    HINIC3_OVS_FLOW_ERROR_POLICY_ID_INSERT_FAIL,
    HINIC3_OVS_FLOW_ERROR_RTE_FLOW_CREATE_FAIL,
    HINIC3_OVS_FLOW_ERROR_FLOW_DESTROY_INPUT_NULL,
    HINIC3_OVS_FLOW_ERROR_DEL_BATCH_CONTEXT_ALLOC_FAIL,
    HINIC3_OVS_FLOW_ERROR_DEL_BATCH_PER_TABLE_ALLOC_FAIL,
    HINIC3_OVS_FLOW_ERROR_CALLBACK_EXTRA_INFO_MEMCPY_FAIL,
    HINIC3_OVS_FLOW_ERROR_CALLBACK_INFO_NULL,
    HINIC3_OVS_FLOW_ERROR_UFID_MAP_ADD_FLOW_SMAC_NULL,
    HINIC3_OVS_FLOW_ERROR_UFID_MAP_GET_TIME_FAIL,
    HINIC3_OVS_FLOW_ERROR_UFID_MAP_ALLOC_HW_ELE_FAIL,
    HINIC3_OVS_FLOW_ERROR_UFID_MAP_ADD_RTE_FLOW_HW_ELE_NULL,
    HINIC3_OVS_FLOW_ERROR_UFID_MAP_ALLOC_HW_BRIEF_FAIL,
    HINIC3_OVS_FLOW_ERROR_UFID_MAP_ALLOC_SW_BRIEF_FAIL,
    // 命令行模块
    HINIC3_CMD_ERROR_SW_UFID_FORMAT_ERROR,
    HINIC3_CMD_ERROR_EXCESSIVE_COMMAND,
    HINIC3_CMD_ERROR_INCOMPLETE_COMMAND,
    // UFID_MAP模块
    HINIC3_UFID_MAP_ERROR_HMAP_NODE_FAIL,
    HINIC3_UFID_MAP_ERROR_GET_HW_ELEMENT_FAIL,
    HINIC3_UFID_MAP_ERROR_FLOW_GET_BY_KEY_FAIL,
    HINIC3_ERRSTAT_END
};

enum hinic3_errstat_level {
    HINIC3_ERRSTAT_LEVEL_ERROR,
    HINIC3_ERRSTAT_LEVEL_WARNING
};

struct hinic3_error_stats {
    enum hinic3_module module;
    enum hinic3_errstat_level level;
    uint64_t count;
    const char *string;
};

void hinic3_add_error_stats(enum hinic3_errstat_type index, uint32_t count);
int hinic3_get_error_stats(enum hinic3_errstat_type index, struct hinic3_error_stats* stats);
#endif