/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2021 Huawei Technologies Co., Ltd
 */

#ifndef HINIC3_UI_STRING_H
#define HINIC3_UI_STRING_H

/* common cmd ui string */
#define HINIC3_UI_LEADING_SIGN_INFO "Info: "
#define HINIC3_UI_LEADING_SIGN_ERROR "Error: "
#define HINIC3_UI_LEADING_SIGN_WARNING "Warning: "
#define HINIC3_UI_LEADING_SIGN_FAILURE "Failure: "
#define HINIC3_UI_EMPTY_STRING ""
#define HINIC3_UI_INDENT_SPACE ""
#define HINIC3_UI_ERROR_UNRECOGNIZED_COMMAND "Unrecognized command"
#define HINIC3_UI_ERROR_WRONG_PARAMETER "Wrong parameter"
#define HINIC3_UI_ERROR_INCOMPLETE_COMMAND "Incomplete command"
#define HINIC3_UI_ERROR_TOO_MANY_PARAMETER "Too many parameters"

enum hinic3_ui_indent
{
    INDENT_0 = 0,
    INDENT_2 = 2,
    INDENT_4 = 4,
    INDENT_5 = 5,
};

/* ufid map cmd ui string */
#define HINIC3_COMMAND_HELP_INFO ", please input -h or --help to get help info!\n"
#define HINIC3_UI_UFID_MAP_ERROR_STRING "Info: %s in ufid table %d table_id %u: %u\n"
#define HINIC3_UI_UFID_MAP_DUMP_START_ERROR_STRING "Dump hardware ufid start error.\n"
#define HINIC3_UI_UFID_MAP_HW_UFID_FORMART_ERROR_STRING "Wrong parameter, hardware ufid format is invalid, should: xxxxxxxx-xxxxxxxx.\n"
#define HINIC3_UI_UFID_TABLE_ID_FORMART_ERROR_STRING "Table id is invalid, should: 0-12.\n"
#define HINIC3_UI_UFID_MAP_SW_UFID_FORMART_ERROR_STRING \
    "Wrong parameter, software ufid format is invalid, should: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.\n"
#define HINIC3_UI_UFID_MAP_SW_DUMP_ERROR_STRING "Dump ufid map error, too many maps, total hw ufid: %zd\n"
#define HINIC3_UI_UFID_MAP_HW_DUMP_ERROR_STRING "Dump ufid map error, too many maps, total hw ufid %zd in table %u\n"
#define HINIC3_UI_UFID_MAP_RTE_FLOW_ITEMS_STRING "  All %zd software flows exist\n"
#define HINIC3_UI_UFID_MAP_HARD_WARE_FLOW_ITEMS_STRING "  Subtable %u has %zd hardware flows exist\n"
#define HINIC3_UI_UFID_MAP_NO_SOFT_WARE_FLOW_ITEMS_STRING "No software flows exist.\n"
#define HINIC3_UI_UFID_MAP_HW_FLOW_NUM_PER_SUB_TABLE_STRING "  All %zd hardware flows exist in ufid table %u:\n"
#define HINIC3_UI_UFID_MAP_HW_FLOW_ITEMS_STRING "  All %zd hardware flows exist\n"
#define HINIC3_UI_UFID_MAP_SUBTABLE_SW_FLOW_ITEMS_STRING "  Subtable %u has %zd software flows:\n"
#define HINIC3_UI_HW_UFID_STRING "Hardware Ufid"
#define HINIC3_UI_SW_UFID_STRING "Mega Ufid"
#define HINIC3_UI_UFID_MAP_HW_DUMP_HELP_TIPS_STRING \
    "dpak-ovs-ctl hwoff/dump-ufid-map-hw { all | <hw-ufid> | -n | { -h | --help } }\n\n"
#define HINIC3_UI_UFID_MAP_HW_DUMP_NUM_HELP_STRING "-n           Dump the number of hardware ufids in ufid tables\n"
#define HINIC3_UI_UFID_MAP_HW_DUMP_SINGLE_HELP_STRING \
    "<hw-ufid>    Dump all software ufids mapped to the given hardware ufids\n"
#define HINIC3_UI_UFID_MAP_HW_DUMP_ALL_HELP_STRING "all          Dump all hardware ufids\n"
#define HINIC3_UI_UFID_MAP_SW_DUMP_HELP_TIPS_STRING \
    "dpak-ovs-ctl hwoff/dump-ufid-map-sw { all | <sw-ufid> | -n | { -h | --help } }\n\n"
#define HINIC3_UI_UFID_MAP_SW_DUMP_NUM_HELP_STRING "-n           Dump the number of software ufids in ufid tables\n"
#define HINIC3_UI_UFID_MAP_SW_DUMP_SINGLE_HELP_STRING \
    "<sw-ufid>    Dump all hardware ufids mapped to the given software ufids\n"
#define HINIC3_UI_UFID_MAP_SW_DUMP_ALL_HELP_STRING "all          Dump all software ufids\n"
#define HINIC3_UI_UFID_MAP_DUMP_HELP_STRING "-h, --help   Display the help information\n"
/* flow show api info cmd ui string */
#define HINIC3_UI_FLOW_OPTION_LIST_STRING "Options list: "
#define HINIC3_UI_FLOW_INPUT_UNKOWN_OPTION_STRING "Unknown option %s.\n"
#define HINIC3_UI_FLOW_REQUIRES_WRONG_ARGUMENT_STRING \
    "Wrong parameter, required %d argument(s), please input -h or --help to get help info.\n"
#define HINIC3_UI_FLOW_DELETE_BY_UFID_SUCCESS "Delete flow by ufid success.\n"
#define HINIC3_UI_FLOW_SHOW_FLOW_API_HELP_STRING \
    "Usage: dpak-ovs-ctl hwoff/show-flow-api { all | clear { all | <api-name> } | api <api-name> | { -h | --help } }\n"
#define HINIC3_UI_FLOW_SHOW_ONE_API_HELP_STRING "api <api-name>           Show info about a specified api\n"
#define HINIC3_UI_FLOW_CLEAR_ONE_API_HELP_STRING "clear <api-name>         Clear info about a specified api\n"
#define HINIC3_UI_FLOW_SHOW_ALL_API_HELP_STRING "all                      Show all api info\n"
#define HINIC3_UI_FLOW_CLEAR_ALL_API_HELP_STRING "clear all                Clear all api info\n"
#define HINIC3_UI_FLOW_HELP_STRING "-h, --help               Display the help information\n"
#define HINIC3_UI_FLOW_ALL_API_TIPS_STRING "api names that can be input are as follows"
#define HINIC3_UI_FLOW_OPTIONS_WRONG_ARGUMENTS_STRING "Option %s required %d argument.\n"
#define HINIC3_UI_FLOW_ALLOC_RECORDS_ERROR_STRING "Alloc api record faild.\n"
#define HINIC3_UI_FLOW_CLEAR_RECORDS_FAILED_STRING "Clear flow api record failed [%s].\n"
#define HINIC3_UI_FLOW_CLEAR_RECORDS_SUCCESS_STRING "Clear flow api record successful [%s].\n"
#define HINIC3_UI_FLOW_QUERY_RECORDS_FAILED_STRING "Query flow api record failed [%s].\n"
#define HINIC3_UI_FLOW_UNKOWN_API_STRING ", api-name is invalid [%s].\n"
#define HINIC3_UI_FLOW_API_COST_MAX_TIME_STRING "Max api time(us):         %" PRIu64 "\n"
#define HINIC3_UI_FLOW_API_COST_MIN_TIME_STRING "Min api time(us):         %" PRIu64 "\n"
#define HINIC3_UI_FLOW_API_COST_AVERAGE_TIME_STRING "Average api time(us):     %" PRIu64 "\n"
#define HINIC3_UI_FLOW_API_TOTAL_CALL_TIMES_STRING "Total call counts:        %" PRIu64 "\n"
#define HINIC3_UI_FLOW_API_ERROR_CALL_TIMES_STRING "Error call counts:        %" PRIu64 "\n"
#define HINIC3_UI_FLOW_API_LATEST_ERROR_CALL_INFO_STRING "Last error info: return %lld in %s"
#define HINIC3_UI_FLOW_API_COUNT_STRING "Api counts: %d\n"
#define HINIC3_UI_FLOW_QUERY_API_NAME_STRING "Query %s:\n"
#define HINIC3_UI_FLOW_ALL_STRING "all"
#define HINIC3_UI_DFX_COMMAND_UPCALL_INFO_HEADER_STRING "Upcall queues info as follows: "
#define HINIC3_UI_DFX_COMMAND_MAX_UPCALL_QUEUE_STRING "Max supported upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_AVAILIBLE_UPCALL_QUEUE_STRING "Availible upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_USED_UPCALL_QUEUE_STRING "Used upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_SHARE_UPCALL_QUEUE_STRING "Share upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_REF_COUNT_STRING "ref count: "
#define HINIC3_UI_DFX_COMMAND_UPCALL_QUEUE_ERROR_STRING "can't dump upcall queue info, errno = "
#define HINIC3_UI_DFX_COMMAND_UPCALL_VIRTUAL_INFO_HEADER_STRING "Upcall virtual queues info as follows: "
#define HINIC3_UI_DFX_COMMAND_MAX_PHYSICAL_QUEUE_STRING "Max physical upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_VIRTUAL_UPCALL_QUEUE_MAX_STRING "Max virtual upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_VIRTUAL_UPCALL_QUEUE_AVAILIABLE_STRING "Total availible virtual upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_GROUP_STRING "Group"
#define HINIC3_UI_DFX_COMMAND_AVAILIBLE_QUEUE_EVERY_GROUP_STRING "availible virtual upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_USED_VIRTUAL_UPCALL_QUEUE_STRING "Used virtual upcall queue num: "
#define HINIC3_UI_DFX_COMMAND_VIRTUAL_QUEUE_ERROR_STRING "can't dump virtual queue info, errno = "
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_ALL_IDLE_STRING "All virtual queues are idle."
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_STRING \
    "Usage: dpak-ovs-ctl hwoff/dump-upcall-queue-info [ -all | -port <port-name> | -virtual <queue-name> | -physical <queue-id> | { -h | --help } ]"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_ALL_FORMAT_STRING "-all"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_ALL_TIPS_STRING \
    "Display all valid virtual queue, eg: hwoff/dump-upcall-queue-info -all"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_PORT_FORMAT_STRING "-port <port-name>"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_PORT_TIPS_STRING \
    "Display the virtual queue list by port, eg: hwoff/dump-upcall-queue-info -port vf0"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_VIRTUAL_FORMAT_STRING "-virtual <queue-name>"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_VIRTUAL_TIPS_STRING \
    "Display the virtual queue list by virtual queue name, eg: hwoff/dump-upcall-queue-info -virtual group0-rx0"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_PHYSICAL_FORMAT_STRING "-physical <queue-id>"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_PHYSICAL_TIPS_STRING \
    "Display the virtual queue list by physical queue id, eg: hwoff/dump-upcall-queue-info -physical 0"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_PORT_ID_ERR_STR "get port id error, invalid port name!"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_VF_DEV_ERR_STR "get vf dev error, invalid port id!"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_PORT_NAME_ERR_STR "get port name error, invalid port id!"
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_FIND_VIRTUAL_QUEUE_ERR_STR "can't find virtual queue %s."
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_PHYSICAL_QUEUE_DEACTIVE_ERR_STR "physical queue %u is deactive."
#define HINIC3_UI_PORT_DUMP_UPCALL_QUEUE_VIRTUAL_QUEUE_DEACTIVE_ERR_STR "virtual queue %s is deactive."
#define HINIC3_UI_PORT_DUMP_QUEUE_NETDEV_ERR_STR "Get netdev error, invalid port name!"
#define HINIC3_UI_PORT_DUMP_QUEUE_PORT_ID_ERR_STR "Dump ports queue info %s failed, get port id error, wrong port name!"
#define HINIC3_UI_PORT_DUMP_QUEUE_DEVICE_IFINDEX_ERR_STR "Dump ports queue info %s failed, device ifindex error!"
#define HINIC3_UI_PORT_GET_VF_LINK_ERR "Port mgmt get vf link state err, ret = %d"
#define HINIC3_DUMP_PORT_GET_BOND_LINK_ERR "Port mgmt get bond link state err, ret = %d"
#define HINIC3_DUMP_PORT_RX_QUEUE_INFO "%2srx queue info:\n"
#define HINIC3_DUMP_PORT_QUEUE_ID "%4squeue-id: %u\n"
#define HINIC3_DUMP_PORT_RX_QUEUE_PKTS "%4srx-pkts:  %lld\n"
#define HINIC3_DUMP_PORT_TX_QUEUE_INFO "%2stx queue info:\n"
#define HINIC3_DUMP_PORT_TX_QUEUE_PKTS "%4stx-pkts:  %lld\n"

/* hinic3 agent flow dump cmd ui string */
#define HINIC3_UI_CMD_USAGE_STRING "Usage: "
#define HINIC3_UI_FLOW_DUMP_HELP_FORMAT_STRING "-h, --help"
#define HINIC3_UI_FLOW_DUMP_HELP_TIPS_STRING "Display the help information"
#define HINIC3_UI_FLOW_DUMP_COUNT_FORMAT_STRING "-n"
#define HINIC3_UI_FLOW_DUMP_COUNT_TIPS_STRING "Obtain the number of all flows"
#define HINIC3_UI_FLOW_DUMP_UFID_FORMAT_STRING "ufid <hw-ufid>"
#define HINIC3_UI_FLOW_DUMP_UFID_TIPS_STRING "Dump flows by hw ufid"
#define HINIC3_UI_FLOW_DUMP_BLOCK_ID_FORMAT_STRING "-i <block-id>"
#define HINIC3_UI_FLOW_DUMP_BLOCK_ID_TIPS_STRING "Dump flows by block id"
#define HINIC3_UI_FLOW_DUMP_FILE_FORMAT_STRING "-f <file-name>"
#define HINIC3_UI_FLOW_DUMP_FILE_TIPS_STRING "Dump all flows to a file"
#define HINIC3_UI_FLOW_DUMP_RTE_FLOW_FILE_FORMAT_STRING "-r [ -f <file-name> ]"
#define HINIC3_UI_FLOW_DUMP_RTE_FILE_TIPS_STRING "Print rte flow info, -f: Dump all rte flows into a file"
#define HINIC3_UI_FLOW_DUMP_CHECK_FORMAT_STRING "check"
#define HINIC3_UI_FLOW_DUMP_CHECK_TIPS_STRING "Check the schedule of dumping flows to a file"
#define HINIC3_UI_FLOW_DUMP_STOP_FORMAT_STRING "stop"
#define HINIC3_UI_FLOW_DUMP_STOP_TIPS_STRING "Stop dumping flows to a file"
#define HINIC3_UI_FLOW_DUMP_GET_FLOW_COUNT_FAILED_STRING "Failed to get current flow counts."
#define HINIC3_UI_FLOW_DUMP_GET_BLOCK_SIZE_FAILED_STRING "Failed to get block size."
#define HINIC3_UI_FLOW_DUMP_BLOCK_ID_ERROR_STRING "Invalid block id."
#define HINIC3_UI_FLOW_GET_BLOCK_ID_FROM_FLOW_FAILED_STRING "Failed to get block id."
#define HINIC3_UI_ACL_DUMP_GROUP_ID_STRING "group-id: "
#define HINIC3_UI_ACL_DUMP_GROUP_ID_ERROR_STRING "group id should be INTEGER<0-3>"
#define HINIC3_UI_ACL_DUMP_FAILURE_STRING "Acl dump failed, please check snic.log."
#define HINIC3_UI_DUMP_CONTEXT_INDEX_STRING "context index:"
#define HINIC3_UI_DUMP_CONTEXT_STATUS_STRING "status:"
#define HINIC3_UI_DUMP_CONTEXT_IDLE_STRING "idle"
#define HINIC3_UI_DUMP_CONTEXT_DUMPING_STRING "dumping"
#define HINIC3_UI_DUMP_CONTEXT_THREAD_ID_STRING "thread id"
#define HINIC3_UI_DUMP_CONTEXT_COUNT_STRING "dump count"
#define HINIC3_UI_DUMP_CONTEXT_START_TIME_STRING "start time"
#define HINIC3_UI_DUMP_CONTEXT_RUNNING_TIME_STRING "running time"

#define HINIC3_UI_FLOW_DUMP_FLOW_COUNT_STRING "Info: Current total flow count: %u.\n"
#define HINIC3_UI_FLOW_DUMP_FLOW_COUNT_BY_TABLE_ID_STRING "Info: Current total flow count of table '%u' is '%u'.\n"
#define HINIC3_UI_FLOW_ALLOC_FLOW_INFO_ERROR_STRING "Alloc flow info faild."
#define HINIC3_UI_FLOW_DUMP_RUN_THREAD_FAILED_STRING "Start dump flows running thread failed."
#define HINIC3_UI_FLOW_DUMP_FLOW_ERROR_STRING "Dump flow by hardware ufid failed."
#define HINIC3_UI_FLOW_DUMP_NO_AVALIBLE_FLOW_STRING "No flow available."
#define HINIC3_UI_FLOW_DUMP_NO_SESSION_STRING "No session available.\n"
#define HINIC3_UI_FLOW_TABLE_ID_STRING " table_id: "
#define HINIC3_UI_FLOW_UFID_STRING "ufid: "
#define HINIC3_UI_FLOW_RELATED_UFID_STRING "r_ufid:"
#define HINIC3_UI_FLOW_KEY_FLAG_STRING "key_flags:"
#define HINIC3_UI_FLOW_KEY_STRING "key: "
#define HINIC3_UI_FLOW_MASK_STRING "mask: "
#define HINIC3_UI_FLOW_RAW_KEY_STRING "raw_key: "
#define HINIC3_UI_FLOW_ACTION_STRING "actions: "
#define HINIC3_UI_FLOW_STATISTIC_STRING "statistics: "
#define HINIC3_UI_FLOW_FLAG_STRING "flags:"
#define HINIC3_UI_FLOW_DUMP_STOP_DUMP_TIME_OUT_STRING "Dump all flows into file stopped time out ,please try again."
#define HINIC3_UI_FLOW_DUMP_STOP_DUMP_SUCCESS_STRING "Dump all flows into file stopped. "
#define HINIC3_UI_FLOW_DUMPIMG_TO_FILE_STRING "Being dumping all flows to out file."
#define HINIC3_UI_FLOW_DUMP_TO_FILE_COMPLETE_STRING "Finished dumping all flows to out file."
#define HINIC3_UI_FLOW_DUMP_FLOW_BUSY_STRING "Dump all flows is busy, please try again after a moment."
#define HINIC3_UI_FLOW_DUMP_ALL_FLOW_START_FAILED_STRING "Start dump all flows failed."
#define HINIC3_UI_FLOW_DUMP_ALL_FLOW_START_SUCCESS_STRING "Starting to dump hinic3 flows into file."
#define HINIC3_UI_FLOW_DUMP_ALL_FLOW_TIPS_STRING "Being dumping all hinic3 flows to file, Please try again later !"
#define HINIC3_UI_FLOW_UP_MAX_TIPS_STRING "%2sTotal hardware flows %u more than %u, please dump to file\n"
#define HINIC3_UI_FLOW_WITH_BLOCKID_UP_MAX_TIPS_STRING \
    "Total hardware flows with block_id(%u) %u more than %u, please dump to file\n"
#define HINIC3_UI_FLOW_DUMP_TOTAL_FLOW_STRING "Total flows: "
#define HINIC3_UI_FLOW_UP_DISPLAY_MAX_TIPS_STRING "%sA maximum of %u flows can be displayed.\n"
#define HINIC3_UI_FLOW_DUMP_TOTAL_CT_LOST_PKT_STRING "Total lost ct pkts: "
#define HINIC3_UI_FLOW_MEGA_INDEX_STRING "index: "
#define HINIC3_UI_FLOW_CONNTRACK_KEY_TUPLE_TYPE_STRING "tuple_type: "
#define HINIC3_UI_FLOW_DUMP_RTE_FAILED_STRING "dump rte flows failed."

#define HINIC3_UI_FILE_PATH_MALLOC_TIPS_STRING "Malloc memmory for real path fail!"
#define HINIC3_UI_FILE_DIRECTORY_SIZE_REACH_LIMIT_STRING \
    "%sDirectory (%s) size (%" PRIu64 "MB) reachs or exceeds the limit (%uMB) !\n"
#define HINIC3_UI_FILE_GET_ABSOLUTE_PATH_FAIL_STRING "%sGet absolute file path fail! wrong filename: %s.\n"
#define HINIC3_UI_FILE_PATH_TIPS_STRING "%sResolve path: %s is invalid!\n"
#define HINIC3_UI_FILE_NOT_ABSOLUTE_PATH_STRING "The file path is incorrect, please check the file path.\n"
#define HINIC3_UI_FILE_OPEN_FAILED_STRING "%sCan not open file : %s, please check the file path.\n"
#define HINIC3_UI_FILE_PATH_CREATE_STRING "%sCreating file path: %s.\n"
#define HINIC3_UI_FILE_PATH_APPEND_STRING "%sAppending to file path: %s.\n"
#define HINIC3_UI_FILE_PATH_LENGTH_TIPS_STRING "Filename is too long!\n"
#define HINIC3_UI_FILE_NO_SPACE_STRING "%sNo space left for file: %s.\n"

#define HINIC3_UI_FLOW_PACKET_STRING "packets"
#define HINIC3_UI_FLOW_BYTES_STRING "bytes"
#define HINIC3_UI_FLOW_AGE_TIME_STRING "age"
#define HINIC3_UI_FLOW_LIVE_TIME_STRING "live"
#define HINIC3_UI_FLOW_CT_INFO_STRING "ct_drop"
#define HINIC3_UI_KEY_VNI_STR "vni"
#define HINIC3_UI_KEY_DSCP_STR "dscp"
#define HINIC3_UI_KEY_VXLAN_RSVD "rsvd0"
#define HINIC3_UI_KEY_DP_HASH_STR "dp_hash"
#define HINIC3_UI_KEY_RECIRC_ID_STR "recirc_id"
#define HINIC3_UI_KEY_GRE_PROTOCOL "gre_pro"
#define HINIC3_UI_KEY_GRE_RSVD  "gre_rsvd"
#define HINIC3_UI_KEY_VID_STR "vid"
#define HINIC3_UI_KEY_VLAN_TCI_STR "vlan_tci"
#define HINIC3_UI_KEY_DL_TYPE_STR "dl_type"
#define HINIC3_UI_KEY_NW_SRC_STR "nw_src"
#define HINIC3_UI_KEY_NW_PROTO_STR "nw_protocol"
#define HINIC3_UI_KEY_OUTER_VLAN_STR "outer_vlan"
#define HINIC3_UI_KEY_INNER_VLAN_STR "inner_vlan"
#define HINIC3_UI_KEY_VPORT_STR "vport"
#define HINIC3_UI_KEY_IFINDEX_STR "ifindex"
#define HINIC3_UI_KEY_SRC_MAC_STR "smac"
#define HINIC3_UI_KEY_DST_MAC_STR "dmac"
#define HINIC3_UI_KEY_DST_IP_STR "dst_ip"
#define HINIC3_UI_KEY_SRC_IP_STR "src_ip"
#define HINIC3_UI_KEY_ETH_TYPE_STR "eth_type"
#define HINIC3_UI_KEY_DST_OUT_IP_STR "out_dst_ip"
#define HINIC3_UI_KEY_SRC_OUT_IP_STR "out_src_ip"
#define HINIC3_UI_KEY_ICMP_ID_STR "icmp_id"
#define HINIC3_UI_KEY_ICMP6_ID_STR "icmp6_id"
#define HINIC3_UI_KEY_ICMP_CODE_STR "icmp_code"
#define HINIC3_UI_KEY_ICMP6_CODE_STR "icmp6_code"
#define HINIC3_UI_KEY_DST_PORT_STR "dst_port"
#define HINIC3_UI_KEY_SRC_PORT_STR "src_port"
#define HINIC3_UI_KEY_ETH_TYPE_STR "eth_type"
#define HINIC3_UI_KEY_INNER_ETH_TYPE_STR "inner_type"
#define HINIC3_UI_KEY_ICMP6_TYPE_STR "icmp6_type"
#define HINIC3_UI_KEY_ICMP_TYPE_STR "icmp_type"
#define HINIC3_UI_KEY_CT_STR "ct"
#define HINIC3_UI_KEY_CT_SEQ_LOW_STR "seqlo"
#define HINIC3_UI_KEY_CT_SEQ_HIGH_STR "seqhi"
#define HINIC3_UI_KEY_CT_MAX_WIN_STR "max_win"
#define HINIC3_UI_KEY_CT_SACLE_STR "wscale"
#define HINIC3_UI_KEY_CT_STATE_STR "state"
#define HINIC3_UI_KEY_VXLAN_PUSH_STR "tnl_push"
#define HINIC3_UI_KEY_VXLAN_POP_STR "tnl_pop"
#define HINIC3_UI_KEY_GRE_ENCAP  "gre_encap"
#define HINIC3_UI_KEY_TURE_STR "true"
#define HINIC3_UI_KEY_FALSE_STR "false"
#define HINIC3_UI_KEY_VLAN_PUSH_STR "vlan_push"
#define HINIC3_UI_KEY_VLAN_POP_STR "vlan_pop"
#define HINIC3_UI_KEY_VLAN_PCP_STR "pcp"
#define HINIC3_UI_KEY_VLAN_SET_PRIORITY_STR "set_priority"
#define HINIC3_UI_KEY_VLAN_SET_SMAC_STR "set_smac"
#define HINIC3_UI_KEY_VLAN_SET_DMAC_STR "set_dmac"
#define HINIC3_UI_KEY_VLAN_SET_SIP_STR "set_sip"
#define HINIC3_UI_KEY_VLAN_SET_DIP_STR "set_dip"
#define HINIC3_UI_KEY_VLAN_SET_SPORT_STR "set_sport"
#define HINIC3_UI_KEY_VLAN_SET_DPORT_STR "set_dport"
#define HINIC3_UI_KEY_VLAN_OUTPUT_STR "output"
#define HINIC3_UI_KEY_VLAN_MIRROR_STR "mirror"
#define HINIC3_UI_KEY_DROP "drop"
#define HINIC3_UI_KET_TTL_DEC "dec_ttl"
#define HINIC3_UI_KEY_DP_HASH_STR "dp_hash"
#define HINIC3_UI_KEY_RECIRC_ID_STR "recirc_id"
#define HINIC3_UI_KEY_SAMPLE "sample"
#define HINIC3_UI_KEY_SAMPLE_RATIO "ratio"
#define HINIC3_UI_TCP_STATE_TYPE_CLOSE_STR "closed"
#define HINIC3_UI_TCP_STATE_TYPE_LISTEN_STR "listen"
#define HINIC3_UI_TCP_STATE_TYPE_SYN_SENT_STR "sent"
#define HINIC3_UI_TCP_STATE_TYPE_ESTABLISHED_STR "established"
#define HINIC3_UI_TCP_STATE_TYPE_SYN_RECV_STR "recv"
#define HINIC3_UI_TCP_STATE_TYPE_CLOSE_WAIT_STR "close-wait"
#define HINIC3_UI_TCP_STATE_TYPE_FIN_WAIT_1_STR "fin-wait-1"
#define HINIC3_UI_TCP_STATE_TYPE_LAST_ACK_STR "last-ack"
#define HINIC3_UI_TCP_STATE_TYPE_FIN_WAIT_2_STR "fin-wait-2"
#define HINIC3_UI_TCP_STATE_TYPE_TIME_WAIT_STR "time-wait"
#define HINIC3_UI_TCP_STATE_TYPE_CLOSING_STR "closing"
#define HINIC3_UI_TCP_STATE_TYPE_UNKNOWN_STR "unkown-ct-tcp-state"
#define HINIC3_UI_ACTION_BLOCK_ID_STR "block-id"
#define HINIC3_UI_ACTION_BLOCK_VERSION_STR "block-version"
#define HINIC3_UI_FLOW_OFFLOAD_STRING "is_offload"

#define HINIC3_UI_PORT_NAME_INVALID_STR "Wrong parameter, port_name %s is invalid\n"
#define HINIC3_UI_PORT_ID_INVALID_STR "Wrong parameter, port %s get port id failed\n"
#define HINIC3_UI_PORT_CONFIG_INVALID_STR "Wrong parameter, port %s get port config failed\n"
#define HINIC3_UI_SECURITY_INFO_GET_ERR_STR "get global security filter config failed\n"
#define HINIC3_UI_SRC_MAC_STR "src-mac"
#define HINIC3_UI_ETH_TYPE_GROUP_ID_STR "eth-type-group-%d:\n"
#define HINIC3_UI_ETH_TYPE_STR "eth-type"
#define HINIC3_UI_ETH_TYPE_RELATRE_PORT_STR "relate-ports"

#define HINIC3_UI_INVALID_QOS_ID_STR "Wrong parameter, invalid argument (qos-id is out of range).\n"
#define HINIC3_UI_INVALID_GROUP_ID_STR "Wrong parameter, invalid argument (group is out of range).\n"
#define HINIC3_UI_INVALID_METER_ID_STR "Wrong parameter, invalid argument (meter id is wrong).\n"
#define HINIC3_UI_INVALID_POLICY_ID_STR "Wrong parameter, invalid argument (policy id is wrong).\n"
#define HINIC3_UI_INVALID_PROFILE_ID_STR "Wrong parameter, invalid argument (profile id is wrong).\n"
#define HINIC3_UI_INVALID_PORT_NAME_STR "port name is wrong.\n"
#define HINIC3_UI_INVALID_FUNC_ID_STR "Invalid argument (func-id is wrong)\n"
#define HINIC3_UI_QOS_NOT_EXIST_STR "Invalid argument (qos is not exist in this port type)\n"
#define HINIC3_UI_INVALID_PCI_ID_STR "Invalid argument (pci-id is wrong)\n"
#define HINIC3_UI_QOS_ID_TOO_LONG_STR "qos_id is too long\n"
#define HINIC3_UI_GET_QOS_ERR_STR "Failed to get qos_id.\n"
#define HINIC3_UI_GET_PORT_QOS_ERR_STR "The current port is not bound to qos.\n"
#define HINIC3_UI_EMPTY_QOS_STR "QoS does not exist.\n"
#define HINIC3_UI_POLICY_NO_VM_STR "The current rate limiting policy is not configured on the ports.\n"
#define HINIC3_UI_FIRST_GET_PORT_INFO_ERR_STR "Failed to get the data of sent and received packets for the first time.\n"
#define HINIC3_UI_SECOND_GET_PORT_INFO_ERR_STR "Failed to get the received and sent packet data for the second time.\n"
#define HINIC3_UI_TIME_EXEC_ERR_STR "Get prot info execute time error.\n"
#define HINIC3_UI_KEY_AGE_STR "idle_time(%us) "
#define HINIC3_UI_KEY_QOS_STR "qos"
#define HINIC3_UI_KEY_METER_STR "meter_id"
#define HINIC3_UI_QOS_PIR "PIR"
#define HINIC3_UI_QOS_CIR "CIR"
#define HINIC3_UI_QOS_PBS "PBS"
#define HINIC3_UI_QOS_CBS "CBS"
#define HINIC3_QOS_UNIT_MAX_LEN 30
#define N_PKTS_DROPPED "    n-pkts-dropped:   %u\n"
#define N_BYTES_DROPPED "    n-byte-dropped:   %u\n"
#define QOS_LOSS "  qos-id[%u]\n"
#define METER_INFO "  meter-id[%u]:\n"
#define QOS_INFO "qos-id:"
#define GET_METER_FAILED "Wrong parameter, qos-id is not exist\n"
#define QOS_ACTION_OUTPUT "(qos-id:%u, qos-type:%u), "
#define MULTI_QOS_ACTION_OUTPUT "(qos-id:%u, qos-type:%s), "
#define UNKNOWN_METER_TYPE "The type of meter must be bandwith or pps.\n"
#define GET_METER_FORM_HOVS_FAILED "Get meter_info from hovs failed.\n"
#define OUTPUT_FORMAT_ERROR "There was an output formatting error.\n"

#define HINIC3_UI_GET_ESCAPE_MODE_FAILED "%sGet flow escape mode failed (err:%d).\n"
#define HINIC3_UI_SHOW_NO_FLOW_OFFLOAD_MODE "%sCurrent escape mode: no flow offload.\n"
#define HINIC3_UI_SHOW_ALL_FLOW_OFFLOAD_MODE "%sCurrent escape mode: all flows offload.\n"
#define HINIC3_UI_ESCAPE_MODE_INVALID "%sEscape mode invalid (type:%u).\n"
#define HINIC3_UI_ESCAPE_MODE_SET_FAILED "%sSet escape mode failed (err:%d).\n"
#define HINIC3_UI_ESCAPE_MODE_HELP_TIPS_STRING "hwoff/flow-escape-mode { enable | disable | show | { -h | --help } }"
#define HINIC3_UI_ESCAPE_MODE_ENABLE_FORMAT_STRING "enable"
#define HINIC3_UI_ESCAPE_MODE_ENABLE_TIPS_STRING "Enable the escape mode to not offload flows"
#define HINIC3_UI_ESCAPE_MODE_DISABLE_FORMAT_STRING "disable"
#define HINIC3_UI_ESCAPE_MODE_DISABLE_TIPS_STRING "Disable the escape mode to offload all flows"
#define HINIC3_UI_ESCAPE_MODE_SHOW_FORMAT_STRING "show"
#define HINIC3_UI_ESCAPE_MODE_SHOW_TIPS_STRING "Show the escape mode"
#define HINIC3_UI_ESCAPE_MODE_SHOW_HELP_STRING "-h, --help"
#define HINIC3_UI_ESCAPE_MODE_SHOW_HELP_TIPS_STRING "Display the help information"

#define HINIC3_UI_ITEM_MASK_STRING "mask:"
#define HINIC3_UI_SESSION_ID "session id:"
#define HINIC3_UI_TOS_STR "type_of_service"
#define HINIC3_UI_VTC_STR "vtc_flow"
#define HINIC3_UI_ARP_OP_STR "arp_op"
#define HINIC3_UI_TAG_DATA_STR "tag_data"
#define HINIC3_UI_TAG_INDEX_STR "tag_index"
#define HINIC3_UI_COUNT_ACTION "count"
#define HINIC3_UI_UPCALL_ACTION "upcall"
#define HINIC3_UI_INDIR_ACTION "indir_hand"
#define HINIC3_UI_REMARK_ACTION "remark"
#define HINIC3_UI_DEC_TTL_ACTION "dec_ttl"
#define HINIC3_UI_END "END"
#define HINIC3_GET_STATS_IN_HOVS "Get stats is failed in hvos.\n"

#define HINIC3_EMC_ERROR_MSG_ITEM "Process flow emc item failed."
#define HINIC3_EMC_ERROR_MSG_ACTION "Process flow emc action failed."
#define HINIC3_EMC_ERROR_MSG_REPEATED "Repeatedly offload the flow table."
#define HINIC3_EMC_ERROR_MSG_MEM_ALLOC_FAILED "Alloc memory failed when query flow ufid"
#define HINIC3_EMC_ERROR_MSG_FLOW "Process flow emc failed."
#define HINIC3_EMC_ERROR_MSG_OFFLOAD_HOVS "Offload flow to HOVS failed."
#define HINIC3_EMC_ERROR_MSG_MODIFY_HOVS "Modify flow to HOVS failed."
#define HINIC3_EMC_ERROR_MSG_MODIFY_SESSION "Modify session to HOVS failed."
#define HINIC3_EMC_ERROR_MSG_MODIFY_FLOW_QOS "Modify flow qos to HOVS failed."

#define HINIC3_LOW_LATENCY_CMD_STR "low_latency"
#define HINIC3_HIGH_THROUGHPUT_CMD_STR "high_throughput"
#define HINIC3_SET_FORWARD_MODE_INPUT_ERROR_STRING \
    ", please input -h or --help to get help info!\n"
#define HINIC3_SET_FORWARD_MODE_FAILED_STRING "Set forward mode failed.\n"
#define HINIC3_SET_FORWARD_MODE_SUCCESS_STRING "Set forward mode success.\n"

/* hinic3 meminfo cmd ui string */
#define HINIC3_UI_MEMINFO_UNIT_STRING "Note: Memory unit is Bytes."
#define HINIC3_UI_HUGEPAGE_MEMINFO_UNIT_STRING \
    "Note: Memory unit is Bytes. Available element is number of elements in memory pool."
#define HINIC3_UI_MEMINFO_TOTAL_ALLOCATED_STRING "total allocated:"
#define HINIC3_UI_MEMINFO_AVAILABLE_ELEM_STRING "available element:"
#define HINIC3_UI_HUGEPAGE_MEMINFO_STATISTICS_STRING "Hugepage memory statistics: "
#define HINIC3_UI_HUGEPAGE_MEMINFO_DISABLED_STRING "Hugepage memory statistic is not enabled. "
#define HINIC3_UI_HEAP_STATISTICS_STRING "Heap statistics: "
#define HINIC3_UI_MEMZONE_STATISTICS_STRING "Memzone statistics: "
#define HINIC3_UI_MEMPOOL_STATISTICS_STRING "Mempool statistics: "
#define HINIC3_UI_TOTAL_STATISTICS_STRING "Total statistics: "

/* hinic3 dfx port cmd ui string */
#define HINIC3_UI_DUMP_BOND_SLAVE_STRING "hwoff/dump-bond-slave-info <bond-name>"
#define HINIC3_UI_BOND_TYPE_ERROR_STRING "the port type is not bond"
#define HINIC3_UI_DUMP_BOND_SLAVE_FAILURE_STRING "%scan't dump bond slave info, errno is %d.\n"
#define HINIC3_UI_GET_SLAVE_NAME_STRING "%sFailed to obtain the bond slave name info, errno is %d.\n"
#define HINIC3_UI_FLOW_DUMP_TABLE_ID_ERROR_STRING "Invalid table id."
/* hwoff show hmap flow num ui string */
#define HINIC3_UI_SHOW_HMAP_FLOW_NUM_STRING \
    "dpak-ovs-ctl hwoff/show-hmap-flow-num { [ -t <table-id> ] | { -h | --help } }"
#define HINIC3_UI_SHOW_HMAP_FLOW_NUM_HELP_FORMAT_STRING "-h, --help"
#define HINIC3_UI_SHOW_HMAP_FLOW_NUM_HELP_TIPS_STRING "Show help command"
#define HINIC3_UI_SHOW_HMAP_FLOW_NUM_ID_FORMAT_STRING "-t <table-id>"
#define HINIC3_UI_SHOW_HMAP_FLOW_NUM_ID_TIPS_STRING "Table ID to query flow number in hmap"

/* hwoff agent cmd ui string */
#define HINIC3_UI_DUMP_FLOW_BLOCK_STRING "dpak-ovs-ctl hwoff/dump-flow-block { -a | -i <block-id> | { -h | --help } }"
#define HINIC3_UI_DUMP_FLOW_BLOCK_HELP_FORMAT_STRING "-h, --help"
#define HINIC3_UI_DUMP_FLOW_BLOCK_HELP_TIPS_STRING "Display the help information"
#define HINIC3_UI_DUMP_FLOW_BLOCK_ID_FORMAT_STRING "-i <block-id>"
#define HINIC3_UI_DUMP_FLOW_BLOCK_ID_TIPS_STRING "Dump a single block version"
#define HINIC3_UI_DUMP_FLOW_BLOCK_ALL_FORMAT_STRING "-a"
#define HINIC3_UI_DUMP_FLOW_BLOCK_ALL_TIPS_STRING "Dump all block versions"

/* hwoff log cmd ui string */
#define HINIC3_UI_LOG_LIMIT_CTL_USAGE_STR \
    "Usage: dpak-ovs-ctl hwoff/log-limit-ctl { --disable INTEGER<duration> | --enable | --show | { -h | --help } }"
#define HINIC3_UI_HELP_FORMAT_STR "-h, --help"
#define HINIC3_UI_HELP_TIP_STR "Display the help information"
#define HINIC3_UI_LOG_LIMIT_DISABLE_FORMAT_STR "--disable <duration>"
#define HINIC3_UI_LOG_LIMIT_DISABLE_TIP_STR "Disable log limit with timeout duration (unit: minutes, range: 1-10080)"
#define HINIC3_UI_LOG_LIMIT_ENABLE_FORMAT_STR "--enable"
#define HINIC3_UI_LOG_LIMIT_ENABLE_TIP_STR "Enable log limit"
#define HINIC3_UI_LOG_LIMIT_SHOW_FORMAT_STR "--show"
#define HINIC3_UI_LOG_LIMIT_SHOW_TIP_STR "Display current status"
#define HINIC3_UI_PLEASE_HELP_STR "please input -h or --help to get help info!"
#define HINIC3_UI_LOG_LIMIT_DISABLED_WARN_STR "Log limit is disabled, may generate massive logs! Reset countdown: %s."
#define HINIC3_UI_LOG_LIMIT_ENABLED_INFO_STR "Log limit is enabled."
#define HINIC3_UI_LOG_LIMIT_DISABLE_FAIL_STR "duration value must be numeric!"
#define HINIC3_UI_LOG_LIMIT_DISABLE_ERANGE_STR "duration value must be in the range [1, 10080]!"
#define HINIC3_UI_LOG_LIMIT_DEBUG_INFINITE_STR "debug level can not be infinite!"
#define HINIC3_UI_SET_LOG_LEVEL_USAGE_STR "Usage: dpak-ovs-ctl hwoff/set-log-level " \
                                          "{ -m STRING<module-name> -l STRING<level> -t INTEGER<duration> | { -h | --help } }"
#define HINIC3_UI_LOG_LEVEL_MODULE_FORMAT_STR "-m <module-name>"
#define HINIC3_UI_LOG_LEVEL_MODULE_TIP_STR "Module name"
#define HINIC3_UI_LOG_LEVEL_LEVEL_FORMAT_STR "-l <level>"
#define HINIC3_UI_LOG_LEVEL_LEVEL_TIP_STR "Log level"
#define HINIC3_UI_LOG_LEVEL_TIMEOUT_FORMAT_STR "-t <duration>"
#define HINIC3_UI_LOG_LEVEL_TIMEOUT_TIP_STR "Timeout duration: enter 1-10080 (minutes) or 'infinite' for no timeout"
#define HINIC3_UI_LOG_LEVEL_SUPPORT_MODULES_STR "Support modules:"
#define HINIC3_UI_LOG_LEVEL_SUPPORT_LEVELS_STR "Support levels:"

#define HINIC3_UI_OPTION_LIST_STRING "Options list: "

#define HINIC3_UI_SET_FORWARD_MODE_TIPS_STRING \
    "hwoff/set-forward-mode { low_latency | high_throughput | { -h | --help } }"
#define HINIC3_UI_SET_FORWARD_MODE_HELP_LOW_STR "Set the packet forwarding mode to low-latency mode"
#define HINIC3_UI_SET_FORWARD_MODE_HELP_HIGH_STR "Set the packet forwarding mode to high-bandwidth mode"

#define HINIC3_UI_DUMP_QOS_LOSS_TIPS_STRING "hwoff/dump-qos-loss { INTEGER<1-1023> | { -h | --help } }"
#define HINIC3_UI_DUMP_QOS_STAT_HRLP_TITLE_STRING "INTEGER<0-1023>"
#define HINIC3_UI_DUMP_QOS_LOSS_HRLP_TITLE_STRING "INTEGER<1-1023>"
#define HINIC3_UI_DUMP_QOS_LOSS_HELP_STR \
    "Query the number of packets discarded in the inbound direction by the rate limiting policy for the specified QoS IDs"

#define HINIC3_UI_DUMP_BOND_SLAVE_TIPS_STRING "hwoff/dump-bond-slave-info { <bond-name> | { -h | --help } }"
#define HINIC3_UI_DUMP_BOND_SLAVE_HELP_BOND_STR "<bond-name>"
#define HINIC3_UI_DUMP_BOND_SLAVE_HELP_STR "Bond Interface Name"

#define HINIC3_UI_SHOW_PORT_QOS_TIPS_STRING "hwoff/show-port-qos { <port-name> | { -h | --help } }"
#define HINIC3_UI_SHOW_PORT_QOS_HELP_NAME_STR "<port-name>"
#define HINIC3_UI_SHOW_PORT_QOS_HELP_STR "Port Interface Name"

#define HINIC3_UI_DUMP_QOS_TIPS_STRING "hwoff/dump-qos [ INTEGER<1-1023> | { -h | --help } ]"
#define HINIC3_UI_DUMP_QOS_HELP_STR \
    "Queries the corresponding rate limiting information based on the ID. Value range: 0-1023"

#define HINIC3_UI_SHOW_PORT_SECURITY_TIPS_STRING "hwoff/show-port-security-filter { <port-name> | { -h | --help } }"
#define HINIC3_UI_SHOW_PORT_SECURITY_HELP_STR "Port Interface Name"

#define HINIC3_UI_DUMP_FLOW_QOS_LOSS_TIPS_STRING "hwoff/dump-flow-qos-loss { INTEGER<0-1023> | { -h | --help } }"
#define HINIC3_UI_DUMP_FLOW_QOS_LOSS_HELP_STR \
    "Queries the corresponding rate limiting information based on the ID. Value range: 0-1023"
#define HINIC3_UI_DUMP_FLOW_QOS_STAT_HELP_STR \
    "Queries the corresponding rate limiting information based on the ID. Value range: 1-1023"

#define HINIC3_UI_SHOW_QOS_SPEED_TIPS_STRING "hwoff/show-qos-speed { INTEGER<1-1023> | { -h | --help } }"
#define HINIC3_UI_SHOW_QOS_SPEED_HELP_STR "The ID generated by the rate limiting policy. Value range: 1-1023"

#define HINIC3_UI_DEL_FLOW_BY_UFID_TIPS_STRING "hwoff/del-flow-by-ufid { <ufid> | { -h | --help } }"
#define HINIC3_UI_DEL_FLOW_BY_UFID_HELP_UFID_STR "<ufid>"
#define HINIC3_UI_DEL_FLOW_BY_UFID_HELP_STR "Unique Flow Identifier (UFID) of the flow entry"

#define HINIC3_UI_TRACE_FLOW_TIPS_STRING                                                                                \
    "hwoff/trace-flow  { -proto <tcp,udp> -sip ENUM<IP<X.X.X.X>,IPV6<X:X::X:X>> -dip ENUM<IP<X.X.X.X>,IPV6<X:X::X:X>> " \
    "-sport INTEGER<0-65535> -dport INTEGER<0-65535> | { -h | --help } }"
#define HINIC3_UI_TRACE_FLOW_PROTO_STR "-proto"
#define HINIC3_UI_TRACE_FLOW_PROTO_HELP_STR "Layer 4 protocol type, ENUM<TCP,UDP>"
#define HINIC3_UI_TRACE_FLOW_SIP_STR "-sip"
#define HINIC3_UI_TRACE_FLOW_SIP_HELP_STR "Source IP address"
#define HINIC3_UI_TRACE_FLOW_DIP_STR "-dip"
#define HINIC3_UI_TRACE_FLOW_DIP_HELP_STR "Destination IP address"
#define HINIC3_UI_TRACE_FLOW_SPORT_STR "-sport"
#define HINIC3_UI_TRACE_FLOW_SPORT_HELP_STR "Source port"
#define HINIC3_UI_TRACE_FLOW_DPORT_STR "-dport"
#define HINIC3_UI_TRACE_FLOW_DPORT_HELP_STR "Destination port"
#define HINIC3_UI_DUMP_METER_TIPS_STRING "hwoff/dump-meter  [ INTEGER<0-1023> | { -h | --help } ]"
#define HINIC3_UI_DUMP_METER_HELP_STR \
    "Queries the corresponding rate limiting information based on the ID. Value range: 0-1023"

#define HINIC3_UI_DUMP_RTE_FLOW_HELP_STR "-r"
#define HINIC3_UI_DUMP_DP_HASH_HELP_STR "Print rte flow info"
#define HINIC3_UI_DUMP_FUZZY_TIPS_STRING "hwoff/dump-fuzzy-flows [ -r | { -h | --help } ]"
#define HINIC3_UI_DUMP_DP_HASH_TIPS_STRING "hwoff/dump-dp-hash-flows [ -r | { -h | --help } ]"

#define HINIC3_UI_DUMP_ACL_TIPS_STRING "hwoff/dump-acl-flow [ -m | -g <group_id> | -r [ -m ] | { -h | --help } ]"
#define HINIC3_UI_DUMP_M_STR "-m"
#define HINIC3_UI_DUMP_ACL_HELP_M_STR "Query ACLs and output the masks simultaneously"
#define HINIC3_UI_DUMP_G_STR "-g <group_id>"
#define HINIC3_UI_DUMP_ACL_HELP_G_STR "Specify the ACL group for the query, with the group_id ranging from 0 to 3"
#define HINIC3_UI_DUMP_R_M_STR "-r [ -m ]"

#define HINIC3_UI_SHOW_METER_TIPS_STRING "hwoff/show-meter { <meter_id> | { -h | --help } }"
#define HINIC3_UI_SHOW_METER_STR "<meter_id>"
#define HINIC3_UI_SHOW_METER_HELP_STR "Query the corresponding meter information based on the meter_id"

#define HINIC3_UI_SHOW_POLICY_TIPS_STRING "hwoff/show-policy { <policy_id> | { -h | --help } }"
#define HINIC3_UI_SHOW_POLICY_STR "<policy_id>"
#define HINIC3_UI_SHOW_POLICY_HELP_STR "Query the corresponding policy information based on the policy_id"

#define HINIC3_UI_SHOW_PROFILE_TIPS_STRING "hwoff/show-profile { <profile_id> | { -h | --help } }"
#define HINIC3_UI_SHOW_PROFILE_STR "<profile_id>"
#define HINIC3_UI_SHOW_PROFILE_HELP_STR "Query the corresponding profile information based on the profile_id"

#define HINIC3_UI_DUMP_PORT_QOS_LOST_TIPS_STRING "hwoff/dump-port-qos-loss { <port-name> | { -h | --help } }"

#define HINIC3_UI_SHOW_PORT_QOS_SPEED_TIPS_STRING "hwoff/show-port-qos-speed { <port-name> | { -h | --help } }"

#define HINIC3_UI_DUMP_QOS_STATS_TIPS_STRING "hwoff/dump-qos-stats { INTEGER<1-1023> | { -h | --help } }"

#define HINIC3_UI_DUMP_PORT_QOS_STATS_TIPS_STRING "hwoff/dump-port-qos-stats { <port-name> | { -h | --help } }"

#define HINIC3_UI_DUMP_FLOW_QOS_TIPS_STRING "hwoff/dump-flow-qos { INTEGER<0-1023> | { -h | --help } }"

#define HINIC3_UI_DUMP_FLOW_QOS_STATS_TIPS_STRING "hwoff/dump-flow-qos-stats { INTEGER<0-1023> | { -h | --help } }"
#define HINIC3_UI_DUMP_FLOW_QOS_LOST_TIPS_STRING "hwoff/dump-flow-qos-loss { INTEGER<0-1023> | { -h | --help } }"

/* hwoff packet detect mode cmd ui string */
#define HINIC3_UI_DETECT_MODE_USAGE_STR \
    "Usage: dpak-ovs-ctl hwoff/packet-detect-mode { --enable | --disable | --show | { -h | --help } }"
#define HINIC3_UI_DETECT_MODE_DISABLE_FORMAT_STR "--disable"
#define HINIC3_UI_DETECT_MODE_DISABLE_TIP_STR "Disable packet detect mode"
#define HINIC3_UI_DETECT_MODE_ENABLE_TIP_STR "Enable packet detect mode"
#endif
