/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
 */

#ifndef _HINIC3_BASE_H_
#define _HINIC3_BASE_H_

/*
 * DPDK 21.11 renamed all ethdev macros from ETH_* to RTE_ETH_*.
 * For DPDK < 21.11 (i.e. 19.11/20.11), map the new names back to the old ones.
 */
#ifndef DPDK_21_11

/* Link speed capabilities */
#define RTE_ETH_LINK_SPEED_AUTONEG  ETH_LINK_SPEED_AUTONEG
#define RTE_ETH_LINK_SPEED_FIXED    ETH_LINK_SPEED_FIXED
#define RTE_ETH_LINK_SPEED_10M_HD   ETH_LINK_SPEED_10M_HD
#define RTE_ETH_LINK_SPEED_10M      ETH_LINK_SPEED_10M
#define RTE_ETH_LINK_SPEED_100M_HD  ETH_LINK_SPEED_100M_HD
#define RTE_ETH_LINK_SPEED_100M     ETH_LINK_SPEED_100M
#define RTE_ETH_LINK_SPEED_1G       ETH_LINK_SPEED_1G
#define RTE_ETH_LINK_SPEED_2_5G     ETH_LINK_SPEED_2_5G
#define RTE_ETH_LINK_SPEED_5G       ETH_LINK_SPEED_5G
#define RTE_ETH_LINK_SPEED_10G      ETH_LINK_SPEED_10G
#define RTE_ETH_LINK_SPEED_20G      ETH_LINK_SPEED_20G
#define RTE_ETH_LINK_SPEED_25G      ETH_LINK_SPEED_25G
#define RTE_ETH_LINK_SPEED_40G      ETH_LINK_SPEED_40G
#define RTE_ETH_LINK_SPEED_50G      ETH_LINK_SPEED_50G
#define RTE_ETH_LINK_SPEED_56G      ETH_LINK_SPEED_56G
#define RTE_ETH_LINK_SPEED_100G     ETH_LINK_SPEED_100G

/* Link speed numeric values */
#define RTE_ETH_SPEED_NUM_NONE      ETH_SPEED_NUM_NONE
#define RTE_ETH_SPEED_NUM_10M       ETH_SPEED_NUM_10M
#define RTE_ETH_SPEED_NUM_100M      ETH_SPEED_NUM_100M
#define RTE_ETH_SPEED_NUM_1G        ETH_SPEED_NUM_1G
#define RTE_ETH_SPEED_NUM_2_5G      ETH_SPEED_NUM_2_5G
#define RTE_ETH_SPEED_NUM_5G        ETH_SPEED_NUM_5G
#define RTE_ETH_SPEED_NUM_10G       ETH_SPEED_NUM_10G
#define RTE_ETH_SPEED_NUM_20G       ETH_SPEED_NUM_20G
#define RTE_ETH_SPEED_NUM_25G       ETH_SPEED_NUM_25G
#define RTE_ETH_SPEED_NUM_40G       ETH_SPEED_NUM_40G
#define RTE_ETH_SPEED_NUM_50G       ETH_SPEED_NUM_50G
#define RTE_ETH_SPEED_NUM_56G       ETH_SPEED_NUM_56G
#define RTE_ETH_SPEED_NUM_100G      ETH_SPEED_NUM_100G
#define RTE_ETH_SPEED_NUM_UNKNOWN   ETH_SPEED_NUM_UNKNOWN

/* Link status */
#define RTE_ETH_LINK_UP             ETH_LINK_UP
#define RTE_ETH_LINK_DOWN           ETH_LINK_DOWN
#define RTE_ETH_LINK_AUTONEG        ETH_LINK_AUTONEG
#define RTE_ETH_LINK_FIXED          ETH_LINK_FIXED
#define RTE_ETH_LINK_FULL_DUPLEX    ETH_LINK_FULL_DUPLEX
#define RTE_ETH_LINK_HALF_DUPLEX    ETH_LINK_HALF_DUPLEX

/* Multi-queue modes */
#define RTE_ETH_MQ_RX_RSS_FLAG      ETH_MQ_RX_RSS_FLAG
#define RTE_ETH_MQ_RX_DCB_FLAG      ETH_MQ_RX_DCB_FLAG
#define RTE_ETH_MQ_RX_VMDQ_FLAG     ETH_MQ_RX_VMDQ_FLAG
#define RTE_ETH_MQ_RX_NONE          ETH_MQ_RX_NONE
#define RTE_ETH_MQ_RX_RSS           ETH_MQ_RX_RSS
#define RTE_ETH_MQ_RX_DCB           ETH_MQ_RX_DCB
#define RTE_ETH_MQ_RX_DCB_RSS       ETH_MQ_RX_DCB_RSS
#define RTE_ETH_MQ_RX_VMDQ_ONLY     ETH_MQ_RX_VMDQ_ONLY
#define RTE_ETH_MQ_RX_VMDQ_RSS      ETH_MQ_RX_VMDQ_RSS
#define RTE_ETH_MQ_RX_VMDQ_DCB      ETH_MQ_RX_VMDQ_DCB
#define RTE_ETH_MQ_RX_VMDQ_DCB_RSS  ETH_MQ_RX_VMDQ_DCB_RSS
#define RTE_ETH_MQ_TX_NONE          ETH_MQ_TX_NONE
#define RTE_ETH_MQ_TX_DCB           ETH_MQ_TX_DCB
#define RTE_ETH_MQ_TX_VMDQ_DCB      ETH_MQ_TX_VMDQ_DCB
#define RTE_ETH_MQ_TX_VMDQ_ONLY     ETH_MQ_TX_VMDQ_ONLY

/* RSS offload types */
#define RTE_ETH_RSS_IPV4            ETH_RSS_IPV4
#define RTE_ETH_RSS_FRAG_IPV4       ETH_RSS_FRAG_IPV4
#define RTE_ETH_RSS_NONFRAG_IPV4_TCP ETH_RSS_NONFRAG_IPV4_TCP
#define RTE_ETH_RSS_NONFRAG_IPV4_UDP ETH_RSS_NONFRAG_IPV4_UDP
#define RTE_ETH_RSS_NONFRAG_IPV4_SCTP ETH_RSS_NONFRAG_IPV4_SCTP
#define RTE_ETH_RSS_NONFRAG_IPV4_OTHER ETH_RSS_NONFRAG_IPV4_OTHER
#define RTE_ETH_RSS_IPV6            ETH_RSS_IPV6
#define RTE_ETH_RSS_FRAG_IPV6       ETH_RSS_FRAG_IPV6
#define RTE_ETH_RSS_NONFRAG_IPV6_TCP ETH_RSS_NONFRAG_IPV6_TCP
#define RTE_ETH_RSS_NONFRAG_IPV6_UDP ETH_RSS_NONFRAG_IPV6_UDP
#define RTE_ETH_RSS_NONFRAG_IPV6_SCTP ETH_RSS_NONFRAG_IPV6_SCTP
#define RTE_ETH_RSS_NONFRAG_IPV6_OTHER ETH_RSS_NONFRAG_IPV6_OTHER
#define RTE_ETH_RSS_L2_PAYLOAD      ETH_RSS_L2_PAYLOAD
#define RTE_ETH_RSS_IPV6_EX         ETH_RSS_IPV6_EX
#define RTE_ETH_RSS_IPV6_TCP_EX     ETH_RSS_IPV6_TCP_EX
#define RTE_ETH_RSS_IPV6_UDP_EX     ETH_RSS_IPV6_UDP_EX
#define RTE_ETH_RSS_PORT            ETH_RSS_PORT
#define RTE_ETH_RSS_VXLAN           ETH_RSS_VXLAN
#define RTE_ETH_RSS_GENEVE          ETH_RSS_GENEVE
#define RTE_ETH_RSS_NVGRE           ETH_RSS_NVGRE
#define RTE_ETH_RSS_GTPU            ETH_RSS_GTPU
#define RTE_ETH_RSS_L3_SRC_ONLY     ETH_RSS_L3_SRC_ONLY
#define RTE_ETH_RSS_L3_DST_ONLY     ETH_RSS_L3_DST_ONLY
#define RTE_ETH_RSS_L4_SRC_ONLY     ETH_RSS_L4_SRC_ONLY
#define RTE_ETH_RSS_L4_DST_ONLY     ETH_RSS_L4_DST_ONLY
#define RTE_ETH_RSS_IP              ETH_RSS_IP
#define RTE_ETH_RSS_UDP             ETH_RSS_UDP
#define RTE_ETH_RSS_TCP             ETH_RSS_TCP
#define RTE_ETH_RSS_SCTP            ETH_RSS_SCTP
#define RTE_ETH_RSS_TUNNEL          ETH_RSS_TUNNEL
#define RTE_ETH_RSS_PROTO_MASK      ETH_RSS_PROTO_MASK
#define RTE_ETH_RSS_RETA_SIZE_64    ETH_RSS_RETA_SIZE_64
#define RTE_ETH_RSS_RETA_SIZE_128   ETH_RSS_RETA_SIZE_128
#define RTE_ETH_RSS_RETA_SIZE_256   ETH_RSS_RETA_SIZE_256
#define RTE_ETH_RSS_RETA_SIZE_512   ETH_RSS_RETA_SIZE_512

/* VLAN offload/mask */
#define RTE_ETH_VLAN_STRIP_OFFLOAD  ETH_VLAN_STRIP_OFFLOAD
#define RTE_ETH_VLAN_FILTER_OFFLOAD ETH_VLAN_FILTER_OFFLOAD
#define RTE_ETH_VLAN_EXTEND_OFFLOAD ETH_VLAN_EXTEND_OFFLOAD
#define RTE_ETH_QINQ_STRIP_OFFLOAD  ETH_QINQ_STRIP_OFFLOAD
#define RTE_ETH_VLAN_STRIP_MASK     ETH_VLAN_STRIP_MASK
#define RTE_ETH_VLAN_FILTER_MASK    ETH_VLAN_FILTER_MASK
#define RTE_ETH_VLAN_EXTEND_MASK    ETH_VLAN_EXTEND_MASK
#define RTE_ETH_QINQ_STRIP_MASK     ETH_QINQ_STRIP_MASK
#define RTE_ETH_VLAN_ID_MAX         ETH_VLAN_ID_MAX

/* RX offloads */
#define RTE_ETH_RX_OFFLOAD_VLAN_STRIP       DEV_RX_OFFLOAD_VLAN_STRIP
#define RTE_ETH_RX_OFFLOAD_IPV4_CKSUM       DEV_RX_OFFLOAD_IPV4_CKSUM
#define RTE_ETH_RX_OFFLOAD_UDP_CKSUM        DEV_RX_OFFLOAD_UDP_CKSUM
#define RTE_ETH_RX_OFFLOAD_TCP_CKSUM        DEV_RX_OFFLOAD_TCP_CKSUM
#define RTE_ETH_RX_OFFLOAD_TCP_LRO          DEV_RX_OFFLOAD_TCP_LRO
#define RTE_ETH_RX_OFFLOAD_QINQ_STRIP       DEV_RX_OFFLOAD_QINQ_STRIP
#define RTE_ETH_RX_OFFLOAD_OUTER_IPV4_CKSUM DEV_RX_OFFLOAD_OUTER_IPV4_CKSUM
#define RTE_ETH_RX_OFFLOAD_MACSEC_STRIP     DEV_RX_OFFLOAD_MACSEC_STRIP
#define RTE_ETH_RX_OFFLOAD_HEADER_SPLIT     DEV_RX_OFFLOAD_HEADER_SPLIT
#define RTE_ETH_RX_OFFLOAD_VLAN_FILTER      DEV_RX_OFFLOAD_VLAN_FILTER
#define RTE_ETH_RX_OFFLOAD_VLAN_EXTEND      DEV_RX_OFFLOAD_VLAN_EXTEND
#define RTE_ETH_RX_OFFLOAD_JUMBO_FRAME      DEV_RX_OFFLOAD_JUMBO_FRAME
#define RTE_ETH_RX_OFFLOAD_SCATTER          DEV_RX_OFFLOAD_SCATTER
#define RTE_ETH_RX_OFFLOAD_TIMESTAMP        DEV_RX_OFFLOAD_TIMESTAMP
#define RTE_ETH_RX_OFFLOAD_SECURITY         DEV_RX_OFFLOAD_SECURITY
#define RTE_ETH_RX_OFFLOAD_KEEP_CRC         DEV_RX_OFFLOAD_KEEP_CRC
#define RTE_ETH_RX_OFFLOAD_SCTP_CKSUM       DEV_RX_OFFLOAD_SCTP_CKSUM
#define RTE_ETH_RX_OFFLOAD_OUTER_UDP_CKSUM  DEV_RX_OFFLOAD_OUTER_UDP_CKSUM
#define RTE_ETH_RX_OFFLOAD_RSS_HASH         DEV_RX_OFFLOAD_RSS_HASH
#define RTE_ETH_RX_OFFLOAD_CHECKSUM         DEV_RX_OFFLOAD_CHECKSUM
#define RTE_ETH_RX_OFFLOAD_VLAN             DEV_RX_OFFLOAD_VLAN

/* TX offloads */
#define RTE_ETH_TX_OFFLOAD_VLAN_INSERT      DEV_TX_OFFLOAD_VLAN_INSERT
#define RTE_ETH_TX_OFFLOAD_IPV4_CKSUM       DEV_TX_OFFLOAD_IPV4_CKSUM
#define RTE_ETH_TX_OFFLOAD_UDP_CKSUM        DEV_TX_OFFLOAD_UDP_CKSUM
#define RTE_ETH_TX_OFFLOAD_TCP_CKSUM        DEV_TX_OFFLOAD_TCP_CKSUM
#define RTE_ETH_TX_OFFLOAD_SCTP_CKSUM       DEV_TX_OFFLOAD_SCTP_CKSUM
#define RTE_ETH_TX_OFFLOAD_TCP_TSO          DEV_TX_OFFLOAD_TCP_TSO
#define RTE_ETH_TX_OFFLOAD_UDP_TSO          DEV_TX_OFFLOAD_UDP_TSO
#define RTE_ETH_TX_OFFLOAD_OUTER_IPV4_CKSUM DEV_TX_OFFLOAD_OUTER_IPV4_CKSUM
#define RTE_ETH_TX_OFFLOAD_QINQ_INSERT      DEV_TX_OFFLOAD_QINQ_INSERT
#define RTE_ETH_TX_OFFLOAD_VXLAN_TNL_TSO    DEV_TX_OFFLOAD_VXLAN_TNL_TSO
#define RTE_ETH_TX_OFFLOAD_GRE_TNL_TSO      DEV_TX_OFFLOAD_GRE_TNL_TSO
#define RTE_ETH_TX_OFFLOAD_IPIP_TNL_TSO     DEV_TX_OFFLOAD_IPIP_TNL_TSO
#define RTE_ETH_TX_OFFLOAD_GENEVE_TNL_TSO   DEV_TX_OFFLOAD_GENEVE_TNL_TSO
#define RTE_ETH_TX_OFFLOAD_MACSEC_INSERT    DEV_TX_OFFLOAD_MACSEC_INSERT
#define RTE_ETH_TX_OFFLOAD_MT_LOCKFREE      DEV_TX_OFFLOAD_MT_LOCKFREE
#define RTE_ETH_TX_OFFLOAD_MULTI_SEGS       DEV_TX_OFFLOAD_MULTI_SEGS
#define RTE_ETH_TX_OFFLOAD_MBUF_FAST_FREE   DEV_TX_OFFLOAD_MBUF_FAST_FREE
#define RTE_ETH_TX_OFFLOAD_SECURITY         DEV_TX_OFFLOAD_SECURITY
#define RTE_ETH_TX_OFFLOAD_UDP_TNL_TSO      DEV_TX_OFFLOAD_UDP_TNL_TSO
#define RTE_ETH_TX_OFFLOAD_IP_TNL_TSO       DEV_TX_OFFLOAD_IP_TNL_TSO
#define RTE_ETH_TX_OFFLOAD_OUTER_UDP_CKSUM  DEV_TX_OFFLOAD_OUTER_UDP_CKSUM

/* Flow control */
#define RTE_ETH_FC_NONE     RTE_FC_NONE
#define RTE_ETH_FC_RX_PAUSE RTE_FC_RX_PAUSE
#define RTE_ETH_FC_TX_PAUSE RTE_FC_TX_PAUSE
#define RTE_ETH_FC_FULL     RTE_FC_FULL

/* RETA */
#define RTE_ETH_RETA_GROUP_SIZE RTE_RETA_GROUP_SIZE

/* VMDQ/DCB */
#define RTE_ETH_VMDQ_MAX_VLAN_FILTERS   ETH_VMDQ_MAX_VLAN_FILTERS
#define RTE_ETH_DCB_NUM_USER_PRIORITIES ETH_DCB_NUM_USER_PRIORITIES
#define RTE_ETH_VMDQ_DCB_NUM_QUEUES     ETH_VMDQ_DCB_NUM_QUEUES
#define RTE_ETH_DCB_NUM_QUEUES          ETH_DCB_NUM_QUEUES
#define RTE_ETH_DCB_PG_SUPPORT            ETH_DCB_PG_SUPPORT
#define RTE_ETH_DCB_PFC_SUPPORT           ETH_DCB_PFC_SUPPORT
#define RTE_ETH_DCB_NUM_TCS               ETH_DCB_NUM_TCS
#define RTE_ETH_MAX_VMDQ_POOL             ETH_MAX_VMDQ_POOL
#define RTE_ETH_NUM_RECEIVE_MAC_ADDR      ETH_NUM_RECEIVE_MAC_ADDR
#define RTE_ETH_VMDQ_NUM_UC_HASH_ARRAY    ETH_VMDQ_NUM_UC_HASH_ARRAY
#define RTE_ETH_VMDQ_ACCEPT_UNTAG         ETH_VMDQ_ACCEPT_UNTAG
#define RTE_ETH_VMDQ_ACCEPT_HASH_MC       ETH_VMDQ_ACCEPT_HASH_MC
#define RTE_ETH_VMDQ_ACCEPT_HASH_UC       ETH_VMDQ_ACCEPT_HASH_UC
#define RTE_ETH_VMDQ_ACCEPT_BROADCAST     ETH_VMDQ_ACCEPT_BROADCAST
#define RTE_ETH_VMDQ_ACCEPT_MULTICAST     ETH_VMDQ_ACCEPT_MULTICAST
#define RTE_ETH_4_TCS                     ETH_4_TCS
#define RTE_ETH_8_TCS                     ETH_8_TCS
#define RTE_ETH_8_POOLS                   ETH_8_POOLS
#define RTE_ETH_16_POOLS                  ETH_16_POOLS
#define RTE_ETH_32_POOLS                  ETH_32_POOLS
#define RTE_ETH_64_POOLS                  ETH_64_POOLS

#endif /* !DPDK_21_11 */

/*
 * DPDK 20.11 renamed RTE_KDRV_* to RTE_PCI_KDRV_*, and
 * RTE_DEV_WHITELISTED/BLACKLISTED to RTE_DEV_ALLOWED/BLOCKED.
 */
#ifndef DPDK_20_11
#define RTE_PCI_KDRV_VFIO        RTE_KDRV_VFIO
#define RTE_PCI_KDRV_IGB_UIO     RTE_KDRV_IGB_UIO
#define RTE_PCI_KDRV_UIO_GENERIC RTE_KDRV_UIO_GENERIC
#define RTE_PCI_KDRV_UNKNOWN     RTE_KDRV_UNKNOWN

#define RTE_DEV_ALLOWED RTE_DEV_WHITELISTED
#define RTE_DEV_BLOCKED RTE_DEV_BLACKLISTED
#endif

#endif /* _HINIC3_BASE_H_ */
